import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'escrituracao', icon: 'i-contabilidade', title: 'Escrituração fiscal', text: 'Reúna documentos, período, situação e pendências antes do fechamento.', dominant: true },
  { key: 'entradas', icon: 'i-compras', title: 'Documentos de entrada', text: 'Acompanhe os documentos recebidos e sua situação fiscal.' },
  { key: 'saidas', icon: 'i-comercial', title: 'Documentos de saída', text: 'Faça o faturamento seguir para livros e apuração sem reconstruir dados.' },
  { key: 'apuracao', icon: 'i-financeiro', title: 'Apuração de impostos', text: 'Apure impostos a partir da escrituração integrada.' },
  { key: 'obrigacoes', icon: 'i-processos', title: 'Livros e obrigações', text: 'Gere livros, Sintegra, Valida-PR, SPED Fiscal e EFD-Reinf.' },
  { key: 'contabilizacao', icon: 'i-grid', title: 'Contabilização', text: 'Controle lotes e lançamentos por período, com Diário e Razão.' },
  { key: 'patrimonio', icon: 'i-custos', title: 'Patrimônio e CIAP', text: 'Acompanhe ativo imobilizado, depreciação e créditos fiscais.' },
  { key: 'demonstrativos', icon: 'i-controladoria', title: 'Demonstrativos contábeis', text: 'Consulte DRE, balanço e balancete, inclusive em estruturas alternativas.' },
];

const flow = [
  { label: 'Operação', input: 'Vendas, compras, folha e financeiro', control: 'Origem de cada movimento', output: 'Documento ou evento identificado' },
  { label: 'Documento', input: 'Entradas, saídas e movimentos', control: 'Dados fiscais e vínculo de origem', output: 'Informação para escriturar' },
  { label: 'Escrituração', input: 'Documentos e lançamentos', control: 'Período, lotes e livros', output: 'Base fiscal organizada' },
  { label: 'Obrigações', input: 'Escrituração do período', control: 'Apuração, livros e arquivos', output: 'Obrigações fiscais preparadas' },
  { label: 'Contabilidade', input: 'Movimentos contabilizados', control: 'Diário, Razão e patrimônio', output: 'DRE, balanço e balancete' },
];

const situations = [
  ['O documento emitido já chegou à escrituração?', 'A origem e a situação do documento permanecem visíveis dentro do período fiscal.'],
  ['Uma entrada possui pendência fiscal?', 'Documentos pendentes ficam destacados para revisão antes do fechamento.'],
  ['O período está pronto para fechar?', 'Processados, pendências, entradas e saídas ajudam a medir o andamento.'],
  ['Existe documento que precisa de revisão?', 'A central fiscal direciona a atenção para o item e sua origem.'],
  ['A informação veio da operação?', 'Compras, vendas, folha e financeiro alimentam os movimentos sem controles paralelos.'],
  ['Onde nasceu aquele lançamento?', 'Documento, origem, período e situação preservam o contexto até a contabilidade.'],
];

const connections = [
  { key: 'comercial', label: 'Comercial', text: 'Faturamento gera documentos e movimentos de venda.', eyebrow: 'Saídas', x: 18, y: 24 },
  { key: 'compras', label: 'Compras', text: 'Entradas geram impactos fiscais, contábeis e patrimoniais.', eyebrow: 'Entradas', x: 82, y: 24 },
  { key: 'financeiro', label: 'Financeiro', text: 'Movimentos financeiros participam da contabilização.', eyebrow: 'Movimentos', x: 14, y: 64 },
  { key: 'controladoria', label: 'Controladoria', text: 'DRE e demonstrativos apoiam a análise gerencial.', eyebrow: 'Demonstrativos', x: 50, y: 82 },
  { key: 'rh', label: 'Recursos Humanos', text: 'Eventos contabilizados da folha seguem para a contabilidade.', eyebrow: 'Folha', x: 86, y: 64 },
];

function capabilityVisual(key) {
  if (key === 'escrituracao') return `<div class="acc-mini-ledger"><header><span>Período 09/2026</span><b>Em andamento</b></header><div><span><small>Documentos</small><b>1.284</b><i style="--w:99.5%"></i></span><span><small>Entradas</small><b>428</b><i style="--w:34%"></i></span><span><small>Saídas</small><b>856</b><i style="--w:67%"></i></span></div><footer><span><i></i>1.277 processados</span><b>7 pendências</b></footer></div>`;
  if (key === 'entradas') return `<div class="acc-mini-docs"><span><i class="ok"></i><b>NF-e 000039508</b><small>Escriturado</small></span><span><i class="warn"></i><b>NF-e 000039510</b><small>Pendente</small></span><span><i class="ok"></i><b>NF-e 000039511</b><small>Escriturado</small></span></div>`;
  if (key === 'saidas') return `<div class="acc-mini-docs"><span><i class="ok"></i><b>NF-e 000059102</b><small>Escriturado</small></span><span><i class="ok"></i><b>NF-e 000059103</b><small>Escriturado</small></span><span><i class="review"></i><b>NF-e 000059104</b><small>Revisão</small></span></div>`;
  if (key === 'apuracao') return `<div class="acc-mini-tax"><small>Apuração do período</small><b>09/2026</b><span><i style="--w:84%"></i></span><em>Base integrada à escrituração</em></div>`;
  if (key === 'obrigacoes') return `<div class="acc-mini-files"><span>SPED Fiscal</span><span>Sintegra</span><span>Valida-PR</span><span>EFD-Reinf</span></div>`;
  if (key === 'contabilizacao') return `<div class="acc-mini-posting"><span class="done">Movimentos</span><i></i><span class="active">Lote contábil</span><i></i><span>Diário e Razão</span></div>`;
  if (key === 'patrimonio') return `<div class="acc-mini-assets"><span><small>Ativo imobilizado</small><b>Controlado</b></span><span><small>Depreciação</small><b>Calculada</b></span><span><small>CIAP</small><b>Integrado</b></span></div>`;
  return `<div class="acc-mini-reports"><span><small>Resultado</small><b>DRE</b></span><span><small>Posição</small><b>Balanço</b></span><span><small>Período</small><b>Balancete</b></span></div>`;
}

function heroProduct() {
  return `<div class="acc-console" aria-label="Exemplo ilustrativo da central fiscal e contábil"><div class="acc-console-top"><span><i></i><i></i><i></i></span><b>Fiscal e Contábil</b><em>Período 09/2026</em></div><div class="acc-console-body"><div class="acc-status"><div><small>Situação</small><strong>Escrituração em andamento</strong></div><span>99,5% processado</span></div><div class="acc-kpis"><div><small>Documentos</small><b>1.284</b></div><div><small>Entradas</small><b>428</b></div><div><small>Saídas</small><b>856</b></div><div class="attention"><small>Pendências</small><b>7</b></div></div><section><span><i style="--w:99.5%"></i></span><div><small>Documentos processados</small><b>1.277 de 1.284</b></div><em>Fechamento do período</em></section></div></div><div class="acc-note acc-note--docs">${icon('i-contabilidade', 'i')}<span><small>Documentos fiscais</small><b>1.284 no período</b></span></div><div class="acc-note acc-note--pending">${icon('i-processos', 'i')}<span><small>Pendências</small><b>7 para revisar</b></span></div><div class="acc-note acc-note--period">${icon('i-grid', 'i')}<span><small>Período fiscal</small><b>09/2026</b></span></div>`;
}

function accountingScreen() {
  const rows = [
    ['000059103', 'Saída', '28/09', 'Comercial', 'Escriturado', 'ok'],
    ['000039510', 'Entrada', '28/09', 'Compras', 'Pendente', 'warn'],
    ['000059104', 'Saída', '29/09', 'Comercial', 'Escriturado', 'ok'],
    ['000039511', 'Entrada', '29/09', 'Compras', 'Revisão', 'review'],
  ];
  return `<div class="acc-screen" role="img" aria-label="Exemplo ilustrativo da central fiscal"><div class="acc-screen-bar"><span><i></i><i></i><i></i></span><b>Fiscal e Contábil · Central fiscal</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="acc-screen-body"><div class="acc-screen-toolbar"><span>Período · 09/2026</span><span>Entradas e saídas</span><b>Escrituração em andamento</b></div><div class="acc-screen-kpis"><span><small>Processados</small><b>1.277</b></span><span><small>Entradas</small><b>428</b></span><span><small>Saídas</small><b>856</b></span><span class="attention"><small>Pendências</small><b>7</b></span></div><div class="acc-screen-layout"><div class="acc-documents"><header><span>Documento</span><span>Tipo</span><span>Emissão</span><span>Origem</span><span>Situação</span></header>${rows.map((row, index) => `<article class="${index === 1 ? 'active' : ''}"><b>${esc(row[0])}</b><span>${esc(row[1])}</span><span>${esc(row[2])}</span><span>${esc(row[3])}</span><em class="${row[5]}">${esc(row[4])}</em></article>`).join('')}</div><aside><span>DOCUMENTO SELECIONADO</span><h3>NF-e 000039510</h3><div><small>Tipo</small><b>Entrada</b></div><div><small>Origem</small><b>Compras</b></div><div><small>Período</small><b>09/2026</b></div><footer><small>Situação</small><b>Pendente de revisão</b></footer></aside></div></div></div>`;
}

export function renderAccounting(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Fiscal e Contábil' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Fiscal e Contábil</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero accounting-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Fiscal e Contábil</p><h1>A informação nasce na operação e chega organizada à contabilidade.</h1><p class="lede">Conecte documentos, escrituração, impostos, livros, patrimônio e demonstrativos sem reconstruir os dados em cada etapa.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_contabilidade_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o período avança${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Origem do lançamento preservada</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product accounting-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section accounting-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro accounting-intro reveal"><p class="kicker">Da operação à escrituração</p><h2>Fiscal e Contabilidade trabalham com a informação que a empresa já gerou.</h2><p>Documentos, lançamentos, apuração, patrimônio e demonstrativos permanecem ligados à origem para reduzir redigitação e facilitar a revisão.</p></div><div id="capacidades" class="module-system-bento accounting-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card accounting-cap-card accounting-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading accounting-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section accounting-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Da operação à contabilidade</p><h2>A informação avança. <span>O contexto permanece.</span></h2><p class="lede">Passe pelas etapas para ver como movimentos operacionais chegam às obrigações e aos demonstrativos.</p></div></div><div class="module-system-flow accounting-flow reveal" data-module-flow><div class="module-system-flow-track accounting-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step accounting-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail accounting-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section accounting-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Uma central fiscal para acompanhar o período.</h2><p class="lede">Documentos, entradas, saídas e pendências aparecem juntos, com a origem do lançamento no painel lateral.</p></div></div><div class="module-system-screen-stage accounting-screen-stage reveal">${accountingScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Período definido</b><small>A escrituração respeita a competência selecionada.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Volume visível</b><small>Entradas e saídas fecham o total de documentos.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Origem preservada</b><small>Compra ou venda acompanha o documento.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Pendência direcionada</b><small>A equipe sabe exatamente o que revisar.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Perguntas do fechamento</p><h2>Situações fiscais que pedem origem e rastreabilidade.</h2></div></div><div class="module-system-situations accounting-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section accounting-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>O fiscal não precisa reconstruir o que a operação já registrou.</h2><p class="lede">As conexões abaixo usam somente integrações descritas no conteúdo atual do Infoline.</p></div></div><div class="module-system-ecosystem accounting-ecosystem reveal"><div class="accounting-ecosystem-top"><span><i></i> Fluxo integrado</span><b>Da operação à escrituração</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="accounting-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="280" rx="258" ry="187"/><path d="M450 246 C355 204 275 160 162 134"/><path d="M450 246 C545 204 625 160 738 134"/><path d="M450 246 C342 276 252 320 126 358"/><path d="M450 246 C450 324 450 386 450 459"/><path d="M450 246 C558 276 648 320 774 358"/></svg><div class="module-system-eco-center accounting-eco-center"><span>${icon('i-contabilidade', 'i')}</span><small>Escrituração</small><b>Fiscal e Contábil</b><em>Origem preservada</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node accounting-eco-node accounting-eco-node--${item.key}" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i accounting-eco-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Fiscal e Contábil</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja documentos, escrituração, apuração, patrimônio e demonstrativos ligados à origem de cada movimento.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_contabilidade_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'accounting.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
