import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'resultado', icon: 'i-controladoria', title: 'Resultado gerencial', text: 'Reúna receita, custos, despesas, resultado e margem em uma leitura executiva.', dominant: true },
  { key: 'diretor', icon: 'i-grid', title: 'Dashboard Diretor', text: 'Acompanhe a visão estratégica do resultado e dos demonstrativos.' },
  { key: 'gestor', icon: 'i-processos', title: 'Dashboard Gestor', text: 'Aprofunde o acompanhamento por grupo, centro e projeto.' },
  { key: 'grupos', icon: 'i-contabilidade', title: 'Resultado por grupo', text: 'Analise o resultado por grupo de contabilização.' },
  { key: 'centros', icon: 'i-custos', title: 'Centros de custo', text: 'Localize onde custos e despesas se concentram na organização.' },
  { key: 'projetos', icon: 'i-comercial', title: 'Rentabilidade por projeto', text: 'Compare projetos e identifique onde a rentabilidade acontece.' },
  { key: 'dre', icon: 'i-contabilidade', title: 'DRE e demonstrativos', text: 'Use DRE, balanço e balancete como base da análise gerencial.' },
  { key: 'caixa', icon: 'i-financeiro', title: 'Fluxo de caixa realizado', text: 'Aproxime o resultado econômico do que efetivamente passou pelo caixa.' },
];

const flow = [
  { label: 'Operação', input: 'Vendas, compras, produção e financeiro', control: 'Origem dos movimentos', output: 'Dados consolidados' },
  { label: 'Custos e receitas', input: 'Valores da operação', control: 'Receitas, custos e despesas', output: 'Composição do resultado' },
  { label: 'Centros', input: 'Movimentos classificados', control: 'Centro, grupo e projeto', output: 'Responsabilidade identificada' },
  { label: 'Resultado', input: 'Receitas, custos e centros', control: 'DRE, margem e rentabilidade', output: 'Variações explicáveis' },
  { label: 'Decisão', input: 'Indicadores gerenciais', control: 'Visão Diretor e Gestor', output: 'Prioridades para agir' },
];

const situations = [
  ['O resultado total é positivo, mas onde ele acontece?', 'Grupos, centros e projetos ajudam a localizar quais partes da empresa sustentam o resultado.'],
  ['A receita cresceu, mas a margem mudou', 'Resultado bruto sobre vendas e DRE aproximam crescimento e rentabilidade.'],
  ['Qual projeto entrega mais rentabilidade?', 'O resumo por projeto permite comparar retorno e contribuição para o resultado.'],
  ['Onde os custos estão concentrados?', 'A leitura por centro de custo direciona a análise para a origem do impacto.'],
  ['Direção e gestão precisam de níveis diferentes', 'Dashboard Diretor resume o cenário; Dashboard Gestor aprofunda grupos e centros.'],
  ['O resultado econômico conversa com o caixa?', 'DRE, demonstrativos e fluxo de caixa realizado permitem observar perspectivas complementares.'],
];

const connections = [
  { key: 'custos', eyebrow: 'Formação econômica', label: 'Gestão de Custos', text: 'Custos reais e formação de preço alimentam a análise gerencial.', x: 18, y: 28 },
  { key: 'contabilidade', eyebrow: 'Demonstrativos', label: 'Fiscal e Contábil', text: 'DRE, balanço e balancete apoiam a leitura do resultado.', x: 82, y: 28 },
  { key: 'financeiro', eyebrow: 'Caixa realizado', label: 'Financeiro', text: 'O fluxo de caixa realizado complementa a visão econômica.', x: 50, y: 78 },
];

function capabilityVisual(key) {
  if (key === 'resultado') return `<div class="ctl-mini-result"><header><span>Resultado do período</span><b>Margem 15,4%</b></header><div><span><small>Receita</small><b>R$ 2,84 mi</b><i style="--w:100%"></i></span><span><small>Custos</small><b>R$ 1,72 mi</b><i style="--w:61%"></i></span><span><small>Despesas</small><b>R$ 684 mil</b><i style="--w:24%"></i></span></div><footer><small>Resultado gerencial</small><strong>R$ 436 mil</strong><em>Fluxo realizado · R$ 391 mil</em></footer></div>`;
  if (key === 'diretor') return `<div class="ctl-mini-kpis"><span><small>Resultado</small><b>R$ 436 mil</b></span><span><small>Margem</small><b>15,4%</b></span></div>`;
  if (key === 'gestor') return `<div class="ctl-mini-bars"><span><small>Industrial</small><i><u style="--w:82%"></u></i><b>31,0%</b></span><span><small>Comercial</small><i><u style="--w:68%"></u></i><b>28,8%</b></span><span><small>Administrativo</small><i><u class="negative" style="--w:42%"></u></i><b>− R$ 684 mil</b></span></div>`;
  if (key === 'grupos') return `<div class="ctl-mini-list"><span><i></i><b>Receita operacional</b><small>R$ 2,84 mi</small></span><span><i></i><b>Custos e despesas</b><small>R$ 2,40 mi</small></span><span><i class="ok"></i><b>Resultado</b><small>R$ 436 mil</small></span></div>`;
  if (key === 'centros') return `<div class="ctl-mini-centers"><span><small>Industrial</small><b>40,8%</b></span><span><small>Comercial</small><b>27,0%</b></span><span><small>Administrativo</small><b>28,5%</b></span><span><small>Outros</small><b>3,7%</b></span></div>`;
  if (key === 'projetos') return `<div class="ctl-mini-project"><span><small>Projeto Alfa</small><b>Rentabilidade 22,6%</b></span><i><u style="--w:72%"></u></i><em>Maior contribuição no período</em></div>`;
  if (key === 'dre') return `<div class="ctl-mini-dre"><span><small>Receita líquida</small><b>R$ 2,84 mi</b></span><span><small>(−) Custos e despesas</small><b>R$ 2,40 mi</b></span><span class="total"><small>Resultado</small><b>R$ 436 mil</b></span></div>`;
  return `<div class="ctl-mini-cash"><span><small>Fluxo realizado</small><b>R$ 391 mil</b></span><i>→</i><span><small>Resultado gerencial</small><b>R$ 436 mil</b></span></div>`;
}

function heroProduct() {
  return `<div class="ctl-console" aria-label="Exemplo ilustrativo do resultado gerencial"><div class="ctl-console-top"><span><i></i><i></i><i></i></span><b>Controladoria</b><em>Visão gerencial · 09/2026</em></div><div class="ctl-console-body"><header><div><small>Resultado gerencial</small><strong>R$ 436.000</strong></div><span>Margem 15,4%</span></header><div class="ctl-console-kpis"><span><small>Receita</small><b>R$ 2.840.000</b></span><span><small>Custos</small><b>R$ 1.720.000</b></span><span><small>Despesas</small><b>R$ 684.000</b></span></div><section><div><small>Resultado gerencial</small><b>R$ 436 mil</b></div><div><small>Margem</small><b>15,4%</b></div><div><small>Fluxo realizado</small><b>R$ 391 mil</b></div></section><footer><span><i style="--w:89.7%"></i></span><small>Fluxo realizado em relação ao resultado gerencial</small></footer></div></div><div class="ctl-note ctl-note--question">${icon('i-controladoria', 'i')}<span><small>Pergunta principal</small><b>Onde o resultado acontece?</b></span></div><div class="ctl-note ctl-note--group">${icon('i-grid', 'i')}<span><small>Resultado por grupo</small><b>3 visões disponíveis</b></span></div>`;
}

function controllershipScreen() {
  const rows = [
    ['Industrial', 'R$ 1.420.000', 'R$ 980.000', 'R$ 440.000', '31,0%', 'positive'],
    ['Comercial', 'R$ 910.000', 'R$ 648.000', 'R$ 262.000', '28,8%', 'positive'],
    ['Outras unidades', 'R$ 510.000', 'R$ 92.000', 'R$ 418.000', '82,0%', 'positive'],
    ['Administrativo', '—', 'R$ 684.000', '− R$ 684.000', '—', 'negative'],
  ];
  return `<div class="ctl-screen" role="img" aria-label="Exemplo ilustrativo de uma visão gerencial"><div class="ctl-screen-bar"><span><i></i><i></i><i></i></span><b>Controladoria · Resultado gerencial</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="ctl-screen-body"><div class="ctl-screen-toolbar"><span>Período · 09/2026</span><span>Visão por unidade e centro</span><b>Dashboard Gestor</b></div><div class="ctl-screen-layout"><div class="ctl-screen-main"><div class="ctl-screen-kpis"><span><small>Receita</small><b>R$ 2,84 mi</b></span><span><small>Custos e despesas</small><b>R$ 2,40 mi</b></span><span class="result"><small>Resultado</small><b>R$ 436 mil</b></span></div><div class="ctl-screen-scroll"><div class="ctl-screen-table"><header><span>Unidade / centro</span><span>Receita</span><span>Custos e despesas</span><span>Resultado</span><span>Margem</span></header>${rows.map((row) => `<article><b>${esc(row[0])}</b><span>${esc(row[1])}</span><span>${esc(row[2])}</span><em class="${row[5]}">${esc(row[3])}</em><span>${esc(row[4])}</span></article>`).join('')}</div></div></div><aside><span>RESULTADO</span><div><small>Resultado gerencial</small><b>R$ 436 mil</b></div><div><small>Margem</small><b>15,4%</b></div><div><small>Fluxo realizado</small><b>R$ 391 mil</b></div><footer><small>Visão</small><b>Consolidada</b></footer></aside></div></div></div>`;
}

export function renderControllership(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Controladoria' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Controladoria</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero controllership-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Controladoria</p><h1>Enxergue onde o resultado acontece — e onde ele muda.</h1><p class="lede">Reúna receitas, custos, despesas, centros e demonstrativos para transformar o que aconteceu na operação em visão gerencial.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_controladoria_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o resultado se forma${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Resultado e margem com contexto</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product controllership-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section controllership-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro controllership-intro reveal"><p class="kicker">Da operação à decisão</p><h2>A Controladoria observa o ERP inteiro.</h2><p>Gestão de Custos explica o produto. Contabilidade organiza os movimentos e demonstrativos. A Controladoria cruza essas informações para mostrar resultado, margem e onde a gestão precisa olhar.</p></div><div id="capacidades" class="module-system-bento controllership-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card controllership-cap-card controllership-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading controllership-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section controllership-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Do movimento à decisão</p><h2>A operação gera os números. <span>A Controladoria explica o resultado.</span></h2><p class="lede">Passe pelas etapas para ver como receitas e custos ganham contexto por centro, grupo e projeto.</p></div></div><div class="module-system-flow controllership-flow reveal" data-module-flow><div class="module-system-flow-track controllership-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step controllership-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail controllership-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section controllership-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Resultado consolidado, com o detalhe que explica cada parte.</h2><p class="lede">A visão gerencial aproxima receita, custos e resultado por unidade, enquanto o painel lateral reúne margem e fluxo realizado.</p></div></div><div class="module-system-screen-stage controllership-screen-stage reveal">${controllershipScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Período definido</b><small>A análise respeita o horizonte da decisão.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Visão consolidada</b><small>Receita e resultado aparecem lado a lado.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Origem do resultado</b><small>Unidades e centros explicam a composição.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Resultado e caixa</b><small>Margem e fluxo realizado completam a leitura.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Perguntas da gestão</p><h2>Situações que pedem mais do que um número consolidado.</h2></div></div><div class="module-system-situations controllership-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section controllership-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>A Controladoria não cria uma operação paralela.</h2><p class="lede">Ela interpreta custos, demonstrativos e caixa realizado a partir da informação que o ERP já registrou.</p></div></div><div class="module-system-ecosystem controllership-ecosystem reveal"><div class="controllership-ecosystem-top"><span><i></i> Visão integrada</span><b>Do registro à decisão</b></div><svg viewBox="0 0 900 540" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="controllership-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 255 C355 225 270 185 162 151"/><path d="M450 255 C545 225 630 185 738 151"/><path d="M450 255 C450 326 450 367 450 421"/></svg><div class="module-system-eco-center controllership-eco-center"><span>${icon('i-controladoria', 'i')}</span><small>Visão gerencial</small><b>Controladoria</b><em>Resultado contextualizado</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node controllership-eco-node controllership-eco-node--${item.key}" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i controllership-eco-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Controladoria</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja dashboards, centros, DRE, rentabilidade e fluxo realizado conectados ao que sua operação já registrou.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_controladoria_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'controllership.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
