import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'composicao', icon: 'i-custos', title: 'Composição do custo', text: 'Entenda quanto materiais, máquina, mão de obra e custos gerais representam no produto.', dominant: true },
  { key: 'materiais', icon: 'i-compras', title: 'Custos dos materiais', text: 'Use insumos e preços para acompanhar o peso da matéria-prima.' },
  { key: 'maquina', icon: 'i-pcpm', title: 'Hora máquina', text: 'Considere o custo de uso das máquinas envolvidas no processo.' },
  { key: 'maoobra', icon: 'i-rh', title: 'Hora homem', text: 'Inclua o custo da mão de obra aplicada em cada atividade.' },
  { key: 'gerais', icon: 'i-grid', title: 'Custos gerais', text: 'Organize outros componentes que participam do custo operacional.' },
  { key: 'centros', icon: 'i-controladoria', title: 'Centros de custo', text: 'Estruture a análise por centro de custo e atividade.' },
  { key: 'preco', icon: 'i-comercial', title: 'Formação de preço', text: 'Forme preço atacadista ou tabela a partir do custo e da margem.' },
  { key: 'margem', icon: 'i-financeiro', title: 'Margem e rentabilidade', text: 'Compare custo, preço, markup e resultado bruto sobre vendas.' },
];

const flow = [
  { label: 'Insumos', input: 'Materiais e preços', control: 'Quantidade e custo', output: 'Custo de matéria-prima' },
  { label: 'Produção', input: 'Estrutura, máquina e mão de obra', control: 'Recursos e atividades', output: 'Custo produtivo' },
  { label: 'Custo', input: 'Materiais e produção', control: 'Composição e centros', output: 'Custo do produto' },
  { label: 'Preço', input: 'Custo conhecido', control: 'Formação e regras', output: 'Preço sugerido' },
  { label: 'Margem', input: 'Custo e preço', control: 'Markup e rentabilidade', output: 'Decisão comercial' },
];

const situations = [
  ['A matéria-prima aumentou de preço', 'O peso dos insumos fica visível na composição para avaliar o impacto no produto.'],
  ['O custo da máquina mudou', 'A hora máquina atualizada ajuda a recalcular o custo produtivo.'],
  ['O produto vende, mas a margem está baixa', 'Custo, preço e rentabilidade aparecem próximos para orientar a decisão.'],
  ['Produtos parecidos têm custos diferentes', 'A composição ajuda a localizar se a diferença está em material, máquina ou mão de obra.'],
  ['O preço não acompanha o custo', 'A formação de preço parte da base atualizada e mostra a margem projetada.'],
  ['Preciso entender de onde veio o custo', 'Cada componente permanece visível para explicar o valor calculado.'],
];

const connections = [
  { key: 'pcpm', eyebrow: 'Estrutura produtiva', label: 'PCPM', text: 'Estrutura e processo produtivo alimentam a composição.', x: 18, y: 27 },
  { key: 'comercial', eyebrow: 'Preço e margem', label: 'Comercial', text: 'Preço, margem e venda usam o custo conhecido.', x: 82, y: 27 },
  { key: 'controladoria', eyebrow: 'Análise do resultado', label: 'Controladoria', text: 'Custos e rentabilidade apoiam a análise do resultado.', x: 50, y: 78 },
];

function capabilityVisual(key) {
  if (key === 'composicao') return `<div class="cost-mini-composition"><header><span>Redutor XP-200</span><b>R$ 431,00</b></header><div><span><i style="--w:66.4%"></i><small>Material</small><b>66,4%</b></span><span><i style="--w:17.4%"></i><small>Máquina</small><b>17,4%</b></span><span><i style="--w:11.9%"></i><small>Mão de obra</small><b>11,9%</b></span><span><i style="--w:4.3%"></i><small>Outros</small><b>4,3%</b></span></div><footer><span>Preço atual · R$ 598,00</span><b>Margem · 27,9%</b></footer></div>`;
  if (key === 'materiais') return `<div class="cost-mini-material"><span><small>Aço SAE 1020</small><b>R$ 184,20</b><em>+ 4,8%</em></span><span><small>Rolamentos</small><b>R$ 64,80</b><em>estável</em></span><span><small>Demais insumos</small><b>R$ 37,40</b><em>- 1,2%</em></span></div>`;
  if (key === 'maquina') return `<div class="cost-mini-rate"><span>${icon('i-pcpm', 'i')}</span><div><small>Centro de usinagem</small><b>R$ 84,00/h</b></div><em>0,89 h/produto</em></div>`;
  if (key === 'maoobra') return `<div class="cost-mini-rate"><span>${icon('i-rh', 'i')}</span><div><small>Montagem</small><b>R$ 51,20</b></div><em>1,60 h</em></div>`;
  if (key === 'gerais') return `<div class="cost-mini-general"><span><b>Energia</b><small>R$ 7,80</small></span><span><b>Terceiros</b><small>R$ 6,40</small></span><span><b>Outros</b><small>R$ 4,40</small></span></div>`;
  if (key === 'centros') return `<div class="cost-mini-centers"><span>Usinagem <i style="--w:78%"></i></span><span>Montagem <i style="--w:54%"></i></span><span>Acabamento <i style="--w:34%"></i></span></div>`;
  if (key === 'preco') return `<div class="cost-mini-price"><span><small>Custo</small><b>R$ 431</b></span><span><small>Margem desejada</small><b>27,9%</b></span><i>→</i><span class="result"><small>Preço</small><b>R$ 598</b></span></div>`;
  return `<div class="cost-mini-margin"><span><small>Preço atual</small><b>R$ 598,00</b></span><i><u style="--w:72%"></u></i><footer><span>Markup · 1,39</span><b>Margem · 27,9%</b></footer></div>`;
}

function heroProduct() {
  return `<div class="cost-product" aria-label="Exemplo ilustrativo da composição do custo de um produto"><div class="cost-product-top"><span><i></i><i></i><i></i></span><b>Gestão de Custos</b><em>Custo do produto</em></div><div class="cost-product-body"><div class="cost-product-head"><div><small>Produto</small><strong>Redutor Industrial XP-200</strong></div><span>Estrutura atualizada</span></div><div class="cost-breakdown"><span><small>Material</small><b>R$ 286,40</b></span><span><small>Máquina</small><b>R$ 74,80</b></span><span><small>Mão de obra</small><b>R$ 51,20</b></span><span><small>Outros custos</small><b>R$ 18,60</b></span></div><div class="cost-total"><div><small>Custo calculado</small><b>R$ 431,00</b></div><div><small>Preço de venda</small><b>R$ 598,00</b></div><div class="positive"><small>Margem</small><b>27,9%</b></div></div></div></div>
  <div class="cost-note cost-note--material">${icon('i-compras', 'i')}<span><small>Material</small><b>66,4% do custo</b></span></div><div class="cost-note cost-note--margin">${icon('i-check', 'i')}<span><small>Margem projetada</small><b>27,9%</b></span></div><div class="cost-note cost-note--machine">${icon('i-pcpm', 'i')}<span><small>Hora máquina</small><b>R$ 84,00/h</b></span></div>`;
}

function costScreen() {
  const parts = [
    ['Material', 'R$ 286,40', '66,4%', '66.4%'],
    ['Máquina', 'R$ 74,80', '17,4%', '17.4%'],
    ['Mão de obra', 'R$ 51,20', '11,9%', '11.9%'],
    ['Outros custos', 'R$ 18,60', '4,3%', '4.3%'],
  ];
  return `<div class="cost-screen" role="img" aria-label="Exemplo ilustrativo da composição detalhada do custo"><div class="cost-screen-bar"><span><i></i><i></i><i></i></span><b>Custos · Composição do produto</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="cost-screen-body"><div class="cost-screen-toolbar"><span>Produto · Redutor Industrial XP-200</span><span>Estrutura vigente</span><b>Recalcular custo</b></div><div class="cost-screen-layout"><div class="cost-screen-parts">${parts.map((part) => `<div><span><b>${part[0]}</b><small>${part[1]}</small></span><i><u style="--w:${part[3]}"></u></i><em>${part[2]}</em></div>`).join('')}</div><aside><div><small>Custo total</small><b>R$ 431,00</b></div><div><small>Preço atual</small><b>R$ 598,00</b></div><div class="positive"><small>Margem</small><b>27,9%</b></div></aside></div><footer><span>Centro principal · Usinagem</span><b>Markup · 1,39</b></footer></div></div>`;
}

export function renderCosts(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Gestão de Custos' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Gestão de Custos</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero costs-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Gestão de custos</p><h1>Entenda quanto realmente custa produzir e vender.</h1><p class="lede">Reúna materiais, hora máquina, hora homem e custos gerais para formar preços com margem e rentabilidade visíveis.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_custos_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o custo se forma${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Custo explicado por componente</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product costs-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section costs-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro costs-intro reveal"><p class="kicker">Custo conhecido, preço consciente</p><h2>Por que este produto custa R$ 431,00?</h2><p>A composição aproxima insumos, recursos produtivos e custos gerais do preço de venda. Assim, a margem deixa de ser uma suposição e passa a ter uma base explicável.</p></div><div id="capacidades" class="module-system-bento costs-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card costs-cap-card costs-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading costs-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section costs-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Do insumo à margem</p><h2>O custo se forma antes <span>de o preço chegar ao cliente.</span></h2><p class="lede">Passe pelas etapas para entender como material e produção se transformam em custo, preço e margem.</p></div></div><div class="module-system-flow costs-flow reveal" data-module-flow><div class="module-system-flow-track costs-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step costs-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail costs-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section costs-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Veja de onde veio cada parte do custo calculado.</h2><p class="lede">A composição mostra participação, valor, custo total, preço atual e margem para explicar o produto antes da decisão comercial.</p></div></div><div class="module-system-screen-stage costs-screen-stage reveal">${costScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Produto e estrutura</b><small>A composição parte da estrutura vigente.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Fonte do custo</b><small>Material e produção permanecem separados.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Custo total</b><small>Todos os componentes formam o valor calculado.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Preço e margem</b><small>A rentabilidade fica visível para decidir.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Onde o custo muda a decisão</p><h2>Problemas que pedem uma composição explicável.</h2></div></div><div class="module-system-situations costs-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section costs-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>Produzir, custear, precificar e vender.</h2><p class="lede">O custo conecta estrutura e processo produtivo ao preço, à margem e à análise do resultado.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium costs-ecosystem reveal" data-eco-count="3"><div class="module-system-ecosystem-head"><span><i></i> Fluxo integrado</span><b>Da produção ao resultado</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C355 225 270 180 162 151"/><path d="M450 263 C545 225 630 180 738 151"/><path d="M450 263 C450 330 450 382 450 437"/></svg><div class="module-system-eco-center costs-eco-center"><span>${icon('i-custos', 'i')}</span><small>Formação econômica</small><b>Custos</b><em>Composição e preço</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node costs-eco-node" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Gestão de Custos</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja materiais, recursos, custo, preço e margem funcionando com os dados da sua operação.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_custos_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'costs.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
