import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'funil', icon: 'i-crm', title: 'Funil de oportunidades', text: 'Veja cada oportunidade por etapa, responsável e próximo passo.', dominant: true },
  { key: 'historico', icon: 'i-grid', title: 'Histórico do cliente', text: 'Consulte contatos e interações antes de falar com o cliente.' },
  { key: 'contatos', icon: 'i-user', title: 'Contatos e listas', text: 'Organize pessoas, empresas e origens de oportunidade.' },
  { key: 'atividades', icon: 'i-check', title: 'Follow-ups e atividades', text: 'Registre retornos, lembretes e tarefas de acompanhamento.' },
  { key: 'oportunidades', icon: 'i-comercial', title: 'Oportunidades', text: 'Acompanhe potencial, situação e avanço comercial.' },
  { key: 'responsaveis', icon: 'i-rh', title: 'Carteira por responsável', text: 'Distribua o acompanhamento e enxergue quem cuida de cada conta.' },
  { key: 'workflows', icon: 'i-processos', title: 'Workflows', text: 'Padronize etapas internas do atendimento e do relacionamento.' },
  { key: 'analise', icon: 'i-controladoria', title: 'Dashboards e relatórios', text: 'Analise oportunidades e contatos por período, situação e vendedor.' },
];

const flow = [
  { label: 'Contato', input: 'Cliente, origem e histórico', control: 'Registro da interação', output: 'Relacionamento atualizado' },
  { label: 'Oportunidade', input: 'Necessidade e potencial', control: 'Etapa e responsável', output: 'Negócio acompanhado' },
  { label: 'Atividade', input: 'Próximo passo definido', control: 'Data, tarefa e follow-up', output: 'Retorno programado' },
  { label: 'Proposta', input: 'Oportunidade qualificada', control: 'Contexto para negociação', output: 'Proposta acompanhada' },
  { label: 'Venda', input: 'Negociação convertida', control: 'Histórico compartilhado', output: 'Venda segue ao Comercial' },
];

const situations = [
  ['Um cliente está sem retorno', 'O próximo follow-up fica ligado à oportunidade e ao responsável.'],
  ['A proposta parou no funil', 'Etapa, última interação e próxima atividade ajudam a localizar a pendência.'],
  ['O vendedor precisa do último contato', 'O histórico reúne as interações antes de uma nova conversa.'],
  ['Há oportunidade sem próxima atividade', 'O acompanhamento evidencia negócios que precisam de um novo passo.'],
  ['Preciso analisar a carteira por vendedor', 'Relatórios por responsável e situação ajudam a organizar a atenção comercial.'],
  ['A oportunidade virou venda', 'O relacionamento registrado segue com contexto para o módulo Comercial.'],
];

const connections = [
  { key: 'comercial', eyebrow: 'Conversão em venda', label: 'Comercial', text: 'A oportunidade convertida chega à negociação com histórico.', x: 18, y: 50 },
  { key: 'processos', eyebrow: 'Workflow', label: 'Processos', text: 'Workflows apoiam as etapas internas do atendimento.', x: 82, y: 50 },
];

function capabilityVisual(key) {
  if (key === 'funil') return `<div class="crm-mini-funnel"><header><span>Pipeline comercial</span><b>R$ 428 mil</b></header><div><span><small>Contato</small><b>4</b><i style="--w:78%"></i></span><span><small>Qualificação</small><b>3</b><i style="--w:58%"></i></span><span><small>Proposta</small><b>3</b><i style="--w:43%"></i></span><span><small>Negociação</small><b>2</b><i style="--w:24%"></i></span></div><footer><span>12 oportunidades abertas</span><b>3 retornos hoje</b></footer></div>`;
  if (key === 'historico') return `<div class="crm-mini-history"><span><i></i><b>Hoje · 10:42</b><small>Proposta apresentada</small></span><span><i></i><b>Ontem · 16:20</b><small>Reunião de diagnóstico</small></span><span><i></i><b>24/09 · 09:15</b><small>Primeiro contato</small></span></div>`;
  if (key === 'contatos') return `<div class="crm-mini-contacts"><span><b>MA</b><small>Mariana Alves</small></span><span><b>RC</b><small>Rafael Costa</small></span><span><b>+8</b><small>Outros contatos</small></span></div>`;
  if (key === 'atividades') return `<div class="crm-mini-tasks"><span><i></i><b>Retorno comercial</b><small>Hoje · 14:30</small></span><span><i class="done"></i><b>Enviar apresentação</b><small>Concluída</small></span></div>`;
  if (key === 'oportunidades') return `<div class="crm-mini-value"><small>Valor potencial</small><b>R$ 84.500</b><span>Proposta enviada</span></div>`;
  if (key === 'responsaveis') return `<div class="crm-mini-owner"><span>MS</span><div><small>Responsável</small><b>Mariana Souza</b><em>5 oportunidades ativas</em></div></div>`;
  if (key === 'workflows') return `<div class="crm-mini-workflow"><span class="done">Contato</span><i></i><span class="active">Retorno</span><i></i><span>Proposta</span></div>`;
  return `<div class="crm-mini-analysis"><span><small>Contatos no mês</small><b>46</b></span><span><small>Em proposta</small><b>4</b></span><span><small>Por vendedor</small><b>3 carteiras</b></span></div>`;
}

function heroProduct() {
  return `<div class="crm-product" aria-label="Exemplo ilustrativo de uma oportunidade comercial"><div class="crm-product-top"><span><i></i><i></i><i></i></span><b>CRM · Oportunidade</b><em>Oportunidade #2184</em></div><div class="crm-product-body"><section><div class="crm-product-head"><div><small>Cliente</small><strong>Indústria Alfa</strong></div><span>Proposta enviada</span></div><div class="crm-product-data"><span><small>Valor potencial</small><b>R$ 84.500</b></span><span><small>Responsável</small><b>Mariana</b></span><span><small>Último contato</small><b>Hoje · 10:42</b></span><span><small>Próxima atividade</small><b>Retorno · 28/09</b></span></div><footer><span>${icon('i-check', 'i')} Próximo passo definido</span><b>Apresentar condição comercial</b></footer></section><aside><header><small>Pipeline</small><b>R$ 428 mil</b></header><div><span><i style="--h:88%"></i><small>Contato</small></span><span><i style="--h:68%"></i><small>Qualif.</small></span><span><i class="active" style="--h:49%"></i><small>Proposta</small></span><span><i style="--h:28%"></i><small>Negoc.</small></span></div><footer><b>12</b><small>oportunidades abertas</small></footer></aside></div></div>
  <div class="crm-note crm-note--attention">${icon('i-check', 'i')}<span><small>Precisam de retorno</small><b>3 oportunidades hoje</b></span></div><div class="crm-note crm-note--owner">${icon('i-user', 'i')}<span><small>Carteira</small><b>Mariana · 5 abertas</b></span></div><div class="crm-note crm-note--stage">${icon('i-crm', 'i')}<span><small>Etapa atual</small><b>Proposta enviada</b></span></div>`;
}

function crmScreen() {
  const columns = [
    ['Contato', '4', [['Metal Norte', 'R$ 32 mil', 'Hoje'], ['Logmix', 'R$ 18 mil', 'Amanhã']]],
    ['Qualificação', '3', [['Grupo Atlas', 'R$ 61 mil', 'Hoje'], ['Nova Era', 'R$ 27 mil', '30/09']]],
    ['Proposta', '3', [['Indústria Alfa', 'R$ 84,5 mil', 'Hoje'], ['Orion Peças', 'R$ 46 mil', '29/09']]],
    ['Negociação', '2', [['Técnica Sul', 'R$ 96 mil', 'Hoje']]],
  ];
  return `<div class="crm-screen" role="img" aria-label="Exemplo ilustrativo do pipeline de oportunidades"><div class="crm-screen-bar"><span><i></i><i></i><i></i></span><b>CRM · Pipeline de oportunidades</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="crm-screen-body"><div class="crm-screen-toolbar"><span>Carteira · Todos os responsáveis</span><span>12 oportunidades abertas</span><b>R$ 428 mil no pipeline</b></div><div class="crm-screen-layout"><div class="crm-board">${columns.map((column, columnIndex) => `<section><header><b>${column[0]}</b><span>${column[1]}</span></header>${column[2].map((card, cardIndex) => `<article class="${columnIndex === 2 && cardIndex === 0 ? 'active' : ''}"><b>${card[0]}</b><small>${card[1]}</small><footer><span>${columnIndex === 2 && cardIndex === 0 ? 'Mariana' : 'Responsável'}</span><em>${card[2]}</em></footer></article>`).join('')}</section>`).join('')}</div><aside><span>OPORTUNIDADE</span><h3>Indústria Alfa</h3><div><small>Etapa</small><b>Proposta enviada</b></div><div><small>Último contato</small><b>Hoje · 10:42</b></div><div><small>Próxima atividade</small><b>Retorno comercial · 28/09</b></div><footer><small>Valor potencial</small><b>R$ 84.500</b></footer></aside></div></div></div>`;
}

export function renderCrm(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'CRM' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>CRM</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero crm-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">CRM integrado ao ERP</p><h1>Saiba quem precisa de atenção e qual é o próximo passo.</h1><p class="lede">Organize contatos, oportunidades, follow-ups e responsáveis para que nenhum relacionamento dependa apenas da memória do vendedor.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_crm_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o relacionamento avança${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Próximo passo sempre visível</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product crm-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section crm-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro crm-intro reveal"><p class="kicker">Relacionamento que vira ação</p><h2>O CRM mostra o contexto e o próximo movimento.</h2><p>Histórico, oportunidade, responsável e atividade ficam próximos para orientar a atenção comercial e preparar a venda.</p></div><div id="capacidades" class="module-system-bento crm-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card crm-cap-card crm-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading crm-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section crm-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Do contato à venda</p><h2>Cada interação prepara <span>o próximo passo comercial.</span></h2><p class="lede">Passe pelas etapas para ver como histórico e atividade acompanham a oportunidade até sua conversão.</p></div></div><div class="module-system-flow crm-flow reveal" data-module-flow><div class="module-system-flow-track crm-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step crm-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail crm-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section crm-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Veja o funil sem perder o detalhe da oportunidade.</h2><p class="lede">O pipeline mostra onde cada negócio está; o painel lateral explica quem cuida, o último contato e o próximo retorno.</p></div></div><div class="module-system-screen-stage crm-screen-stage reveal">${crmScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Carteira visível</b><small>As oportunidades aparecem por etapa.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Valor potencial</b><small>O pipeline mostra o volume em aberto.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Responsável definido</b><small>Cada oportunidade tem acompanhamento.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Próximo passo</b><small>Atividade e data orientam o retorno.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Onde o CRM muda a rotina</p><h2>Problemas que pedem contexto e acompanhamento.</h2></div></div><div class="module-system-situations crm-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section crm-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>Relacionamento, workflow e venda no mesmo caminho.</h2><p class="lede">O CRM registra o que acontece antes do pedido e entrega o histórico a quem vende.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium crm-ecosystem reveal" data-eco-count="2"><div class="module-system-ecosystem-head"><span><i></i> Fluxo integrado</span><b>Do relacionamento à venda</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C365 263 285 275 162 280"/><path d="M450 263 C535 263 615 275 738 280"/></svg><div class="module-system-eco-center crm-eco-center"><span>${icon('i-crm', 'i')}</span><small>Relacionamento</small><b>CRM</b><em>Próximo passo visível</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node crm-eco-node" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre o CRM</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja contatos, oportunidades, follow-ups e responsáveis funcionando junto ao Comercial.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_crm_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'crm.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
