import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'pedidos', icon: 'i-ecommerce', title: 'Pedidos dos marketplaces', text: 'Acompanhe os pedidos dos canais digitais junto à operação do ERP.', dominant: true },
  { key: 'canais', icon: 'i-grid', title: 'Shopee e Mercado Livre', text: 'Centralize os canais já integrados ao Infoline.' },
  { key: 'produtos', icon: 'i-comercial', title: 'Produtos e anúncios', text: 'Gerencie produtos e anúncios de marketplace no mesmo contexto.' },
  { key: 'estoque', icon: 'i-wms', title: 'Consulta de estoque', text: 'Consulte disponibilidade antes de o pedido avançar.' },
  { key: 'faturamento', icon: 'i-contabilidade', title: 'Faturamento', text: 'Leve o pedido digital para as rotinas de venda e faturamento.' },
  { key: 'integracao', icon: 'i-processos', title: 'Acompanhamento da integração', text: 'Veja o que entrou no ERP e o que ainda exige atenção.' },
  { key: 'repasses', icon: 'i-financeiro', title: 'Repasses das plataformas', text: 'Acompanhe os repasses dos marketplaces na gestão.' },
  { key: 'analise', icon: 'i-controladoria', title: 'Vendas e faturamento', text: 'Analise vendas por produto e faturamento consolidado.' },
];

const flow = [
  { label: 'Marketplace', input: 'Shopee e Mercado Livre', control: 'Canal, anúncio e produto', output: 'Pedido identificado' },
  { label: 'Pedido', input: 'Compra realizada no canal', control: 'Cliente, itens e valor', output: 'Pedido pronto para integrar' },
  { label: 'ERP', input: 'Pedido do marketplace', control: 'Integração e disponibilidade', output: 'Venda registrada na operação' },
  { label: 'Faturamento', input: 'Pedido integrado', control: 'Situação e documento', output: 'Pedido faturado' },
  { label: 'Acompanhamento', input: 'Venda e retorno do canal', control: 'Integração, vendas e repasses', output: 'Operação digital visível' },
];

const situations = [
  ['Entrou um novo pedido no marketplace', 'O canal, o pedido e seus itens aparecem na central da operação digital.'],
  ['O pedido precisa virar venda no ERP', 'A integração aproxima o pedido do marketplace das rotinas do Comercial.'],
  ['É preciso consultar o saldo do produto', 'A disponibilidade fica próxima do pedido antes de ele avançar.'],
  ['Um pedido exige atenção', 'O acompanhamento da integração ajuda a localizar o que ainda não seguiu o fluxo esperado.'],
  ['O faturamento precisa ser acompanhado', 'Pedido e situação permanecem visíveis no mesmo caminho operacional.'],
  ['A gestão precisa analisar os canais', 'Vendas por produto, faturamento consolidado e repasses apoiam a análise.'],
];

const connections = [
  { key: 'comercial', eyebrow: 'Operação de venda', label: 'Comercial', text: 'Pedidos dos canais seguem para a operação de venda.', x: 18, y: 27 },
  { key: 'wms', eyebrow: 'Disponibilidade', label: 'WMS e Estoque', text: 'A disponibilidade do produto acompanha a operação.', x: 82, y: 27 },
  { key: 'financeiro', eyebrow: 'Repasses', label: 'Financeiro', text: 'Repasses das plataformas entram na gestão financeira.', x: 50, y: 78 },
];

function capabilityVisual(key) {
  if (key === 'pedidos') return `<div class="ecom-mini-orders"><header><span>Pedidos de hoje</span><b>29</b></header><div><span><i class="ml"></i><small>Mercado Livre</small><b>18</b></span><span><i class="shopee"></i><small>Shopee</small><b>11</b></span></div><footer><span><i></i>24 integrados</span><b>2 exigem atenção</b></footer></div>`;
  if (key === 'canais') return `<div class="ecom-mini-channels"><span><i>ML</i><b>Mercado Livre</b><small>Ativo</small></span><span><i>S</i><b>Shopee</b><small>Ativo</small></span></div>`;
  if (key === 'produtos') return `<div class="ecom-mini-products"><span><i></i><b>Kit Ferramentas</b><small>2 anúncios</small></span><span><i></i><b>Rolamento 6204</b><small>3 anúncios</small></span></div>`;
  if (key === 'estoque') return `<div class="ecom-mini-stock"><small>Saldo disponível</small><b>160 un.</b><span><i style="--w:76%"></i></span><em>Atualizado no ERP</em></div>`;
  if (key === 'faturamento') return `<div class="ecom-mini-invoice"><span class="done">Pedido integrado</span><i></i><span>Faturamento</span><i></i><span>Canal</span></div>`;
  if (key === 'integracao') return `<div class="ecom-mini-status"><span><i class="ok"></i><b>Integrados</b><em>24</em></span><span><i class="wait"></i><b>Aguardando</b><em>3</em></span><span><i class="warn"></i><b>Atenção</b><em>2</em></span></div>`;
  if (key === 'repasses') return `<div class="ecom-mini-payout"><small>Repasses acompanhados</small><b>R$ 18.420</b><span>Marketplaces</span></div>`;
  return `<div class="ecom-mini-analysis"><span><small>Vendas por produto</small><b>Visível</b></span><span><small>Faturamento</small><b>Consolidado</b></span><span><small>Integrações</small><b>Acompanhadas</b></span></div>`;
}

function heroProduct() {
  return `<div class="ecom-product" aria-label="Exemplo ilustrativo da central de pedidos dos canais"><div class="ecom-product-top"><span><i></i><i></i><i></i></span><b>E-commerce · Pedidos dos canais</b><em>Hoje</em></div><div class="ecom-product-body"><header><div><small>Pedidos recebidos</small><strong>29</strong></div><span><b>Mercado Livre</b><em>18 pedidos</em></span><span><b>Shopee</b><em>11 pedidos</em></span></header><div class="ecom-product-summary"><span><small>Integrados</small><b>24</b></span><span><small>Aguardando</small><b>3</b></span><span><small>Atenção</small><b>2</b></span></div><section><div><small>Novo pedido · Mercado Livre</small><strong>#20004182</strong></div><span><small>Valor</small><b>R$ 842,00</b></span><span><small>Situação</small><b>Integrado ao ERP</b></span><footer><i></i>Pedido de venda PV 048632 criado</footer></section></div></div><div class="ecom-note ecom-note--order">${icon('i-ecommerce', 'i')}<span><small>Novo pedido</small><b>Mercado Livre #20004182</b></span></div><div class="ecom-note ecom-note--stock">${icon('i-wms', 'i')}<span><small>Estoque consultado</small><b>160 unidades disponíveis</b></span></div><div class="ecom-note ecom-note--erp">${icon('i-check', 'i')}<span><small>Pedido integrado</small><b>PV 048632</b></span></div>`;
}

function ecommerceScreen() {
  const rows = [
    ['Mercado Livre', '20004182', 'R$ 842,00', 'Integrado', 'ok'],
    ['Shopee', '24092188', 'R$ 318,40', 'Faturando', 'run'],
    ['Mercado Livre', '20004191', 'R$ 1.280,00', 'Atenção', 'warn'],
    ['Shopee', '24092204', 'R$ 596,90', 'Novo', 'new'],
  ];
  return `<div class="ecom-screen" role="img" aria-label="Exemplo ilustrativo da central de pedidos digitais"><div class="ecom-screen-bar"><span><i></i><i></i><i></i></span><b>E-commerce · Central de pedidos digitais</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="ecom-screen-body"><div class="ecom-screen-toolbar"><span>Todos os canais</span><span>Hoje</span><b>29 pedidos recebidos</b></div><div class="ecom-screen-layout"><div class="ecom-orders"><header><span>Canal</span><span>Pedido</span><span>Valor</span><span>Situação</span></header>${rows.map((row, index) => `<article class="${index === 2 ? 'active' : ''}"><span><i class="${row[0] === 'Shopee' ? 'shopee' : 'ml'}"></i>${esc(row[0])}</span><b>${esc(row[1])}</b><strong>${esc(row[2])}</strong><em class="${row[4]}">${esc(row[3])}</em></article>`).join('')}</div><aside><span>PEDIDO SELECIONADO</span><h3>Mercado Livre</h3><div><small>Pedido do canal</small><b>20004191</b></div><div><small>Cliente</small><b>Consumidor final</b></div><div><small>Pedido no ERP</small><b>PV 048641</b></div><footer><small>Situação</small><b>Aguardando faturamento</b></footer></aside></div></div></div>`;
}

export function renderEcommerce(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'E-commerce e Marketplaces' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>E-commerce e Marketplaces</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero ecommerce-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">E-commerce e Marketplaces</p><h1>Venda nos marketplaces sem criar uma operação paralela ao ERP.</h1><p class="lede">Traga pedidos de Shopee e Mercado Livre para a mesma base de estoque, venda, faturamento e gestão.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_ecommerce_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver a operação digital${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Pedidos e canais conectados</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product ecommerce-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section ecommerce-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro ecommerce-intro reveal"><p class="kicker">Canais digitais dentro da gestão</p><h2>O pedido online entra na mesma operação da empresa.</h2><p>Canal, produto, estoque, pedido, faturamento e repasse ficam próximos para reduzir controles paralelos.</p></div><div id="capacidades" class="module-system-bento ecommerce-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card ecommerce-cap-card ecommerce-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading ecommerce-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section ecommerce-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Do canal à gestão</p><h2>O pedido digital segue <span>o fluxo do ERP.</span></h2><p class="lede">Passe pelas etapas para ver como o marketplace deixa de ser uma operação isolada.</p></div></div><div class="module-system-flow ecommerce-flow reveal" data-module-flow><div class="module-system-flow-track ecommerce-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step ecommerce-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail ecommerce-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section ecommerce-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Uma central para acompanhar os pedidos digitais.</h2><p class="lede">Veja canal, pedido, valor e situação sem perder o vínculo com a venda criada no ERP.</p></div></div><div class="module-system-screen-stage ecommerce-screen-stage reveal">${ecommerceScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Canal identificado</b><small>Mercado Livre e Shopee aparecem na mesma visão.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Situação visível</b><small>Cada pedido mostra onde está no fluxo.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Pedido no ERP</b><small>A referência comercial acompanha a integração.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Atenção direcionada</b><small>A equipe enxerga o pedido que precisa agir.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Onde a integração muda a rotina</p><h2>Pedidos digitais sem uma operação paralela.</h2></div></div><div class="module-system-situations ecommerce-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section ecommerce-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>Canal, pedido, estoque e gestão no mesmo caminho.</h2><p class="lede">As conexões abaixo refletem integrações já descritas no conteúdo atual do Infoline.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium ecommerce-ecosystem reveal" data-eco-count="3"><div class="module-system-ecosystem-head"><span><i></i> Fluxo integrado</span><b>Do canal à gestão</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C355 225 270 180 162 151"/><path d="M450 263 C545 225 630 180 738 151"/><path d="M450 263 C450 330 450 382 450 437"/></svg><div class="module-system-eco-center ecommerce-eco-center"><span>${icon('i-ecommerce', 'i')}</span><small>Canais digitais</small><b>E-commerce</b><em>Pedidos no mesmo fluxo</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node ecommerce-eco-node" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre E-commerce e Marketplaces</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja pedidos de Shopee e Mercado Livre funcionando junto ao Comercial, ao estoque e à gestão.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_ecommerce_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'ecommerce.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
