import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'fluxo', icon: 'i-financeiro', title: 'Fluxo de caixa', text: 'Compare o previsto e o realizado para enxergar a posição dos próximos dias.', dominant: true },
  { key: 'receber', icon: 'i-comercial', title: 'Contas a receber', text: 'Acompanhe títulos, vencimentos, baixas e valores em aberto.' },
  { key: 'pagar', icon: 'i-compras', title: 'Contas a pagar', text: 'Organize compromissos, liquidações e pagamentos por período.' },
  { key: 'cobranca', icon: 'i-processos', title: 'Cobrança', text: 'Planeje cobranças e acompanhe boletos e títulos em aberto.' },
  { key: 'conciliacao', icon: 'i-check', title: 'Conciliação bancária', text: 'Confira banco e ERP para localizar diferenças e confirmar movimentos.' },
  { key: 'portadores', icon: 'i-grid', title: 'Bancos e portadores', text: 'Consulte saldo anterior, entradas, saídas e saldo atual de bancos e caixas.' },
  { key: 'cnab', icon: 'i-financeiro', title: 'CNAB', text: 'Gere remessas e processe retornos da cobrança bancária.' },
  { key: 'previsao', icon: 'i-controladoria', title: 'Previsão financeira', text: 'Antecipe disponibilidade e compromissos antes que o caixa seja movimentado.' },
];

const flow = [
  { label: 'Venda e compra', input: 'Vendas faturadas e compras recebidas', control: 'Origem e condição financeira', output: 'Movimento identificado' },
  { label: 'Título', input: 'Documento e condição', control: 'Valor, parcela e vencimento', output: 'Conta a pagar ou receber' },
  { label: 'Baixa', input: 'Pagamento ou recebimento', control: 'Liquidação e diferença', output: 'Título atualizado' },
  { label: 'Banco', input: 'Movimentação financeira', control: 'Portador e conciliação', output: 'Saldo confirmado' },
  { label: 'Fluxo de caixa', input: 'Títulos e movimentos', control: 'Previsto e realizado', output: 'Posição para decidir' },
];

const situations = [
  ['Quanto vence hoje?', 'Os títulos do dia aparecem com valor, situação e portador para priorizar a rotina.'],
  ['Quais clientes estão em atraso?', 'Os recebimentos vencidos ficam visíveis para orientar a cobrança.'],
  ['O que precisa ser pago esta semana?', 'Compromissos futuros podem ser consultados por vencimento e valor.'],
  ['A venda foi faturada. Onde está o recebimento?', 'O título mantém a origem comercial e o caminho até a baixa.'],
  ['A compra foi recebida. Onde está o compromisso?', 'A entrada da compra segue para o contas a pagar sem perder o contexto.'],
  ['Qual será a disponibilidade nos próximos dias?', 'O fluxo previsto reúne entradas e saídas antes da movimentação ocorrer.'],
];

const connections = [
  { key: 'comercial', label: 'Comercial', text: 'Vendas e faturamento geram os recebimentos.', eyebrow: 'Recebimentos', x: 18, y: 24 },
  { key: 'compras', label: 'Compras', text: 'Entradas e condições geram compromissos a pagar.', eyebrow: 'Pagamentos', x: 82, y: 24 },
  { key: 'contabilidade', label: 'Fiscal e Contábil', text: 'Documentos e movimentos permanecem integrados.', eyebrow: 'Documentos', x: 14, y: 64 },
  { key: 'controladoria', label: 'Controladoria', text: 'Realizado e projetado apoiam a análise do resultado.', eyebrow: 'Análise', x: 50, y: 82 },
  { key: 'whatsapp', label: 'Integração WhatsApp', text: 'Boletos podem ser enviados ao cliente com acompanhamento da mensagem.', eyebrow: 'Cobrança', x: 86, y: 64 },
];

function capabilityVisual(key) {
  if (key === 'fluxo') return `<div class="fin-mini-flow"><header><span>Próximos 7 dias</span><b>+ R$ 43.550</b></header><div class="fin-mini-bars"><span><i style="--h:45%"></i><u style="--h:32%"></u></span><span><i style="--h:58%"></i><u style="--h:44%"></u></span><span><i style="--h:72%"></i><u style="--h:48%"></u></span><span><i style="--h:61%"></i><u style="--h:66%"></u></span><span><i style="--h:82%"></i><u style="--h:59%"></u></span><span><i style="--h:76%"></i><u style="--h:68%"></u></span><span><i style="--h:92%"></i><u style="--h:74%"></u></span></div><footer><span><i></i>Entradas previstas</span><span><i></i>Saídas previstas</span></footer></div>`;
  if (key === 'receber') return `<div class="fin-mini-list"><span><i class="ok"></i><b>Cliente Alfa</b><small>R$ 18.400</small></span><span><i></i><b>Distribuidora Sul</b><small>R$ 9.860</small></span><span><i class="late"></i><b>Cliente Beta</b><small>Vencido</small></span></div>`;
  if (key === 'pagar') return `<div class="fin-mini-list"><span><i></i><b>Fornecedor A</b><small>Hoje</small></span><span><i></i><b>Transportadora</b><small>28/09</small></span><span><i class="ok"></i><b>Serviços</b><small>Agendado</small></span></div>`;
  if (key === 'cobranca') return `<div class="fin-mini-collection"><span><small>Em aberto</small><b>R$ 32.640</b></span><i><u style="--w:68%"></u></i><footer><span>18 títulos</span><b>6 contatos hoje</b></footer></div>`;
  if (key === 'conciliacao') return `<div class="fin-mini-reconcile"><span><small>Banco</small><b>R$ 84.220</b></span><i>${icon('i-check', 'i')}</i><span><small>ERP</small><b>R$ 84.220</b></span></div>`;
  if (key === 'portadores') return `<div class="fin-mini-accounts"><span><b>Banco principal</b><small>R$ 294.800</small></span><span><b>Caixa</b><small>R$ 18.760</small></span><span><b>Aplicações</b><small>R$ 115.000</small></span></div>`;
  if (key === 'cnab') return `<div class="fin-mini-cnab"><span>${icon('i-financeiro', 'i')}<b>Remessa</b><small>Gerada</small></span><i>→</i><span>${icon('i-check', 'i')}<b>Retorno</b><small>Processado</small></span></div>`;
  return `<div class="fin-mini-forecast"><span><small>Disponível hoje</small><b>R$ 428.560</b></span><i>→</i><span><small>Saldo projetado</small><b>R$ 472.110</b></span></div>`;
}

function heroProduct() {
  return `<div class="fin-console" aria-label="Exemplo ilustrativo de uma central financeira"><div class="fin-console-top"><span><i></i><i></i><i></i></span><b>Financeiro</b><em>Posição consolidada</em></div><div class="fin-console-body"><div class="fin-balance"><div><small>Disponibilidade</small><strong>R$ 428.560</strong></div><span>Atualizado agora</span></div><div class="fin-kpis"><div><small>A receber</small><b>R$ 186.420</b></div><div><small>A pagar</small><b>R$ 142.870</b></div><div class="attention"><small>Vence hoje</small><b>R$ 18.540</b></div></div><div class="fin-projection"><div><small>Saldo projetado</small><b>R$ 472.110</b></div><div class="fin-spark"><i style="--h:28%"></i><i style="--h:42%"></i><i style="--h:38%"></i><i style="--h:56%"></i><i style="--h:63%"></i><i style="--h:72%"></i><i style="--h:86%"></i></div><em>Próximos 7 dias</em></div></div></div>
  <div class="fin-note fin-note--today">${icon('i-grid', 'i')}<span><small>Vencem hoje</small><b>12 títulos</b></span></div><div class="fin-note fin-note--positive">${icon('i-check', 'i')}<span><small>Saldo projetado</small><b>Positivo</b></span></div><div class="fin-note fin-note--overdue">${icon('i-processos', 'i')}<span><small>Valores vencidos</small><b>R$ 8.740</b></span></div>`;
}

function financialScreen() {
  const rows = [
    ['Clientes', 'Receber', 'Hoje', '+ R$ 32.400', 'Previsto', 'ok'],
    ['Fornecedores', 'Pagar', 'Hoje', '- R$ 18.540', 'Programado', 'wait'],
    ['Folha', 'Pagar', '28/09', '- R$ 11.200', 'Previsto', 'run'],
    ['Cobrança bancária', 'Receber', '30/09', '+ R$ 9.860', 'Em aberto', 'wait'],
  ];
  return `<div class="fin-screen" role="img" aria-label="Exemplo ilustrativo da posição financeira"><div class="fin-screen-bar"><span><i></i><i></i><i></i></span><b>Financeiro · Posição financeira</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="fin-screen-body"><div class="fin-screen-toolbar"><span>Período · 25/09 a 02/10</span><span>Todos os portadores</span><b>Atualizar posição</b></div><div class="fin-screen-kpis"><div><small>Receber</small><b>R$ 186.420</b></div><div><small>Pagar</small><b>R$ 142.870</b></div><div class="result"><small>Resultado previsto</small><b>R$ 43.550</b></div></div><div class="fin-screen-scroll"><div class="fin-screen-table"><div class="th"><span>Origem</span><span>Movimento</span><span>Vencimento</span><span>Valor</span><span>Situação</span></div>${rows.map((row) => `<div class="tr"><span>${row[0]}</span><span>${row[1]}</span><span>${row[2]}</span><span>${row[3]}</span><span class="${row[5]}">${row[4]}</span></div>`).join('')}</div></div><footer><span>Saldo atual · R$ 428.560</span><b>Saldo projetado · R$ 472.110</b></footer></div></div>`;
}

export function renderFinancial(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Financeiro' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Financeiro</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero financial-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">ERP financeiro</p><h1>Transforme movimentos da empresa inteira em visão de caixa.</h1><p class="lede">Acompanhe títulos, vencimentos, bancos, cobrança e fluxo previsto e realizado em uma central financeira conectada à operação.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_financeiro_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o caixa se forma${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Posição prevista e realizada</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product financial-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section financial-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro financial-intro reveal"><p class="kicker">Gestão financeira na prática</p><h2>O Financeiro não começa no Financeiro.</h2><p>Vendas geram recebimentos, compras geram compromissos e os movimentos de toda a empresa chegam ao caixa. O Infoline mantém essa origem visível para você decidir com contexto.</p></div><div id="capacidades" class="module-system-bento financial-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card financial-cap-card financial-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading financial-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section financial-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Da operação ao caixa</p><h2>Venda ou compra acontece. <span>O Financeiro recebe o contexto.</span></h2><p class="lede">Passe por cada etapa para ver como o movimento nasce na operação e chega à posição financeira.</p></div></div><div class="module-system-flow financial-flow reveal" data-module-flow><div class="module-system-flow-track financial-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step financial-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail financial-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section financial-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Veja a posição financeira antes de decidir.</h2><p class="lede">Entradas, saídas, vencimentos e saldo projetado permanecem na mesma visão, com os compromissos logo abaixo.</p></div></div><div class="module-system-screen-stage financial-screen-stage reveal">${financialScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Período definido</b><small>A posição respeita o horizonte da decisão.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Entradas e saídas</b><small>Receber e pagar aparecem lado a lado.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Origem preservada</b><small>Cada compromisso mantém seu contexto.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Saldo projetado</b><small>O efeito futuro fica visível antes da baixa.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Perguntas que o caixa precisa responder</p><h2>Situações financeiras que pedem informação no momento certo.</h2></div></div><div class="module-system-situations financial-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section financial-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>O Financeiro recebe o que aconteceu na empresa inteira.</h2><p class="lede">Vendas, compras, documentos, análise e cobrança alimentam a mesma posição financeira.</p></div></div><div class="module-system-ecosystem financial-ecosystem reveal"><div class="financial-ecosystem-top"><span><i></i> Fluxo integrado</span><b>Da operação à posição financeira</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="financial-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="280" rx="258" ry="187"/><path d="M450 246 C355 204 275 160 162 134"/><path d="M450 246 C545 204 625 160 738 134"/><path d="M450 246 C342 276 252 320 126 358"/><path d="M450 246 C450 324 450 386 450 459"/><path d="M450 246 C558 276 648 320 774 358"/></svg><div class="module-system-eco-center financial-eco-center"><span>${icon('i-financeiro', 'i')}</span><small>Posição financeira</small><b>Financeiro</b><em>Previsto e realizado</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node financial-eco-node financial-eco-node--${item.key}" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i financial-eco-arrow')}</a>`; }).join('')}</div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre o Financeiro</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja títulos, bancos, conciliação e fluxo de caixa conectados à operação da sua empresa.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_financeiro_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'financial.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
