import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'folha', icon: 'i-rh', title: 'Folha e cálculos', text: 'Acompanhe colaboradores, processamento, revisões, cálculos e provisões da competência.', dominant: true },
  { key: 'colaboradores', icon: 'i-user', title: 'Colaboradores', text: 'Reúna cadastro completo, cargos e horários usados nas rotinas de pessoal.' },
  { key: 'ponto', icon: 'i-check', title: 'Ponto eletrônico', text: 'Integre informações da jornada ao contexto do colaborador.' },
  { key: 'beneficios', icon: 'i-grid', title: 'Benefícios', text: 'Mantenha benefícios ligados à gestão de pessoas.' },
  { key: 'obrigacoes', icon: 'i-contabilidade', title: 'Obrigações', text: 'Prepare eSocial, CAGED, RAIS, DIRF e SEFIP a partir das rotinas de pessoal.' },
  { key: 'provisoes', icon: 'i-financeiro', title: 'Provisões', text: 'Acompanhe as provisões de folha dentro da competência.' },
  { key: 'saude', icon: 'i-processos', title: 'Saúde e segurança', text: 'Registre informações relacionadas à exposição a agentes nocivos.' },
  { key: 'acompanhamento', icon: 'i-controladoria', title: 'Informe e acompanhamento', text: 'Reúna informe de rendimentos, participação nos resultados e pesquisa de clima.' },
];

const flow = [
  { label: 'Colaborador', input: 'Cadastro, cargo e horário', control: 'Dados do colaborador', output: 'Jornada definida' },
  { label: 'Jornada', input: 'Horário e ponto eletrônico', control: 'Informações da jornada', output: 'Base para a folha' },
  { label: 'Folha', input: 'Colaborador e informações da competência', control: 'Cálculos e provisões', output: 'Folha processada' },
  { label: 'Obrigações', input: 'Dados da folha', control: 'eSocial, CAGED, RAIS, DIRF e SEFIP', output: 'Obrigações preparadas' },
  { label: 'Contabilidade', input: 'Eventos contabilizados da folha', control: 'Vínculo com a competência', output: 'Contabilização' },
];

const situations = [
  ['O ponto está separado da folha?', 'A integração com ponto eletrônico aproxima a jornada dos cálculos de pessoal.'],
  ['Quais colaboradores ainda exigem revisão?', 'A competência reúne colaboradores, cálculos e situação no mesmo contexto.'],
  ['As provisões da folha já foram calculadas?', 'Provisões fazem parte das rotinas disponíveis no módulo.'],
  ['Preciso gerar as obrigações da competência', 'eSocial, CAGED, RAIS, DIRF e SEFIP ficam dentro do conjunto de rotinas de pessoal.'],
  ['Preciso acompanhar benefícios e informações complementares', 'Benefícios, informe de rendimentos e outras rotinas permanecem junto à gestão de pessoas.'],
  ['O que acontece depois que a folha é calculada?', 'Eventos contabilizados da folha permitem que os movimentos sigam para a Contabilidade.'],
];

function capabilityVisual(key) {
  if (key === 'folha') return `<div class="hr-mini-payroll"><header><span>Folha · 09/2026</span><b>Em processamento</b></header><div><span><small>Colaboradores</small><b>186</b></span><span><small>Processados</small><b>174</b></span><span class="attention"><small>Em revisão</small><b>12</b></span></div><section><span><i style="--w:93.5%"></i></span><small>Cálculos · 93,5%</small></section><footer><span>${icon('i-check', 'i')} Provisões calculadas</span><b>Eventos preparados</b></footer></div>`;
  if (key === 'colaboradores') return `<div class="hr-mini-people"><span><i>MS</i><b>Mariana Souza</b><small>Produção</small></span><span><i>RC</i><b>Rafael Costa</b><small>Comercial</small></span><footer>+ 184 colaboradores</footer></div>`;
  if (key === 'ponto') return `<div class="hr-mini-time"><header><span>Jornada</span><b>Hoje</b></header><div><span><small>Entrada</small><b>08:02</b></span><span><small>Intervalo</small><b>12:01</b></span><span><small>Retorno</small><b>13:02</b></span><span><small>Saída</small><b>17:48</b></span></div></div>`;
  if (key === 'beneficios') return `<div class="hr-mini-benefits"><span>${icon('i-check', 'i')}<b>Benefício ativo</b></span><span>${icon('i-check', 'i')}<b>Benefício cadastrado</b></span><span>${icon('i-grid', 'i')}<b>Outros benefícios</b></span></div>`;
  if (key === 'obrigacoes') return `<div class="hr-mini-chips"><span>eSocial</span><span>CAGED</span><span>RAIS</span><span>DIRF</span><span>SEFIP</span></div>`;
  if (key === 'provisoes') return `<div class="hr-mini-provision"><span><small>Competência</small><b>09/2026</b></span><i>${icon('i-check', 'i')}</i><span><small>Situação</small><b>Calculada</b></span></div>`;
  if (key === 'saude') return `<div class="hr-mini-safety"><span>${icon('i-processos', 'i')}</span><div><small>Exposição a agentes nocivos</small><b>Acompanhamento registrado</b></div></div>`;
  return `<div class="hr-mini-follow"><span><small>Informe</small><b>Rendimentos</b></span><span><small>Resultados</small><b>Participação</b></span><span><small>Clima</small><b>Pesquisa</b></span></div>`;
}

function heroProduct() {
  return `<div class="hr-console" aria-label="Exemplo ilustrativo do fechamento da folha"><div class="hr-console-top"><span><i></i><i></i><i></i></span><b>Recursos Humanos</b><em>Folha · 09/2026</em></div><div class="hr-console-body"><header><div><small>Folha 09/2026</small><strong>Em processamento</strong></div><span>93,5% concluído</span></header><div class="hr-console-kpis"><span><small>Colaboradores</small><b>186</b></span><span><small>Processados</small><b>174</b></span><span class="attention"><small>Em revisão</small><b>12</b></span></div><section><small>Cálculos</small><span><i style="--w:93.5%"></i></span><b>174 de 186</b></section><footer><div><small>Ponto eletrônico</small><b>Integrado</b></div><div><small>Provisões</small><b>Calculadas</b></div><div><small>Eventos contabilizados</small><b>Preparados</b></div></footer></div></div><div class="hr-note">${icon('i-check', 'i')}<span><small>Jornada</small><b>Ponto integrado</b></span></div><div class="hr-note">${icon('i-rh', 'i')}<span><small>Folha</small><b>Cálculos e provisões</b></span></div><div class="hr-note">${icon('i-contabilidade', 'i')}<span><small>Obrigações</small><b>eSocial e arquivos legais</b></span></div>`;
}

function hrScreen() {
  const rows = [
    ['MS', 'Mariana Souza', 'ADM', 'Calculado', 'Concluído', 'ok'],
    ['RC', 'Rafael Costa', 'COM', 'Calculado', 'Concluído', 'ok'],
    ['LP', 'Lucas Pereira', 'PROD A', 'Em revisão', 'Atenção', 'warn'],
    ['AM', 'Ana Martins', 'ADM', 'Calculado', 'Concluído', 'ok'],
  ];
  return `<div class="hr-screen" role="img" aria-label="Exemplo ilustrativo do fechamento da folha"><div class="hr-screen-bar"><span><i></i><i></i><i></i></span><b>RH · Fechamento da folha</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="hr-screen-body"><div class="hr-screen-toolbar"><span>Competência · 09/2026</span><span>186 colaboradores</span><b>Folha em cálculo</b></div><div class="hr-screen-kpis"><span><small>Cálculos</small><b>174</b></span><span class="attention"><small>Em revisão</small><b>12</b></span><span><small>Provisões</small><b>Calculadas</b></span></div><div class="hr-screen-layout"><div class="hr-screen-scroll"><div class="hr-screen-table"><header><span>Colaborador</span><span>Horário</span><span>Cálculo</span><span>Situação</span></header>${rows.map((row, index) => `<article class="${index === 2 ? 'active' : ''}"><span><i>${esc(row[0])}</i><b>${esc(row[1])}</b></span><span>${esc(row[2])}</span><span>${esc(row[3])}</span><em class="${row[5]}">${esc(row[4])}</em></article>`).join('')}</div></div><aside><span>COLABORADOR</span><h3>Lucas Pereira</h3><div><small>Cadastro</small><b>Completo</b></div><div><small>Horário</small><b>Produção A</b></div><div><small>Competência</small><b>09/2026</b></div><footer><small>Folha</small><b>Em revisão</b></footer></aside></div></div></div>`;
}

export function renderHr(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Recursos Humanos' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Recursos Humanos</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero hr-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Recursos Humanos</p><h1>Transforme jornada, folha e obrigações em uma rotina única de pessoas.</h1><p class="lede">Conecte colaboradores, horários, ponto eletrônico, cálculos, benefícios e obrigações dentro do mesmo ERP.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_rh_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como a folha avança${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Competência e situação visíveis</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product hr-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section hr-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro hr-intro reveal"><p class="kicker">Pessoas dentro da gestão</p><h2>Cadastro, jornada, folha e obrigações na mesma competência.</h2><p>O contexto do colaborador acompanha a rotina: horários e ponto apoiam os cálculos; folha e provisões preparam obrigações e eventos contabilizados.</p></div><div id="capacidades" class="module-system-bento hr-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card hr-cap-card hr-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading hr-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section hr-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Do colaborador à contabilização</p><h2>A jornada alimenta a folha. <span>A folha prepara o próximo passo.</span></h2><p class="lede">Passe pelas etapas para ver como cadastro, jornada e competência chegam às obrigações e à Contabilidade.</p></div></div><div class="module-system-flow hr-flow reveal" data-module-flow><div class="module-system-flow-track hr-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step hr-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail hr-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section hr-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Uma central para acompanhar o fechamento da folha.</h2><p class="lede">Competência, colaboradores, cálculos e revisões aparecem juntos, com o contexto da pessoa selecionada no painel lateral.</p></div></div><div class="module-system-screen-stage hr-screen-stage reveal">${hrScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Competência definida</b><small>A folha trabalha dentro do período selecionado.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Jornada próxima do cálculo</b><small>Cadastro, horário e ponto permanecem no contexto.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Situação do cálculo</b><small>A equipe identifica quem ainda precisa de atenção.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Eventos preparados</b><small>A folha pode seguir às rotinas contábeis e obrigações.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Perguntas da competência</p><h2>Situações de pessoas que pedem contexto, prazo e acompanhamento.</h2></div></div><div class="module-system-situations hr-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const accounting = modules.contabilidade;
  const integrationSection = `<section class="section hr-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Rotina conectada</p><h2>Jornada entra. Obrigações e eventos contabilizados saem.</h2><p class="lede">Ponto e obrigações aparecem como capacidades da rotina; a Contabilidade é a conexão comprovada com outro módulo do ERP.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium hr-ecosystem reveal" data-eco-count="3"><div class="module-system-ecosystem-head"><span><i></i> Rotina integrada</span><b>Da jornada à contabilização</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C450 220 450 175 450 129"/><path d="M450 263 C350 300 270 370 162 431"/><path d="M450 263 C550 300 630 370 738 431"/></svg><div class="module-system-eco-center hr-eco-center"><span>${icon('i-rh', 'i')}</span><small>Gestão de pessoas</small><b>Recursos Humanos</b><em>Folha e obrigações</em></div><div class="module-system-eco-node module-system-eco-node--info hr-eco-node hr-eco-node--info" style="--x:50%;--y:23%"><span>${icon('i-check', 'i')}</span><div><em>Capacidade</em><b>Ponto eletrônico</b><small>Informações da jornada apoiam as rotinas de pessoal.</small></div></div><div class="module-system-eco-node module-system-eco-node--info hr-eco-node hr-eco-node--info" style="--x:18%;--y:77%"><span>${icon('i-grid', 'i')}</span><div><em>Capacidade</em><b>Obrigações</b><small>Folha alimenta eSocial, CAGED, RAIS, DIRF e SEFIP.</small></div></div><a class="module-system-eco-node hr-eco-node" style="--x:82%;--y:77%" href="${accounting.slug}.html"><span>${icon(accounting.icon, 'i')}</span><div><em>Módulo integrado</em><b>Fiscal e Contábil</b><small>Eventos contabilizados da folha seguem para a contabilização.</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a></div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Recursos Humanos</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja colaboradores, cálculos, ponto eletrônico, benefícios, obrigações e eventos contabilizados trabalhando dentro da mesma gestão.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_rh_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'hr.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
