import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'workflow', icon: 'i-processos', title: 'Workflow automatizado', text: 'Transforme uma rotina em etapas definidas, com estado atual e andamento visível.', dominant: true },
  { key: 'definicao', icon: 'i-grid', title: 'Definição do fluxo', text: 'Organize as etapas que compõem uma rotina.' },
  { key: 'sequencia', icon: 'i-check', title: 'Sequência das etapas', text: 'Garanta que cada atividade avance na ordem definida.' },
  { key: 'responsaveis', icon: 'i-rh', title: 'Responsáveis', text: 'Deixe claro quem conduz cada etapa do fluxo.' },
  { key: 'monitoramento', icon: 'i-controladoria', title: 'Monitoramento', text: 'Acompanhe onde cada processo está durante a execução.' },
  { key: 'padronizacao', icon: 'i-processos', title: 'Padronização', text: 'Faça rotinas semelhantes seguirem o mesmo caminho.' },
  { key: 'transparencia', icon: 'i-grid', title: 'Transparência', text: 'Dê visibilidade sobre o andamento do processo.' },
  { key: 'otimizacao', icon: 'i-check', title: 'Otimização', text: 'Revise o fluxo para reduzir erro, retrabalho e melhorar a eficiência.' },
];

const flow = [
  { label: 'Definir', input: 'Rotina e suas etapas', control: 'Sequência do fluxo', output: 'Processo definido' },
  { label: 'Executar', input: 'Fluxo definido', control: 'Etapa e responsável', output: 'Atividade em andamento' },
  { label: 'Monitorar', input: 'Processo em execução', control: 'Andamento das etapas', output: 'Situação visível' },
  { label: 'Otimizar', input: 'Fluxo acompanhado', control: 'Pontos de melhoria', output: 'Processo mais eficiente' },
];

const situations = [
  ['A equipe não sabe qual é a próxima etapa', 'O workflow organiza as atividades em uma sequência definida.'],
  ['A rotina muda dependendo de quem executa', 'A padronização ajuda processos semelhantes a seguirem o mesmo caminho.'],
  ['Uma atividade ficou parada e ninguém percebeu', 'O acompanhamento torna o andamento do processo visível.'],
  ['Existe muito retrabalho entre as etapas', 'Um fluxo definido reduz margem para erros e repetição desnecessária.'],
  ['Preciso saber quem está conduzindo a atividade', 'Etapas e responsáveis mantêm o contexto da execução.'],
  ['O processo funciona, mas pode melhorar', 'O acompanhamento cria base para revisar e otimizar o fluxo.'],
];

function capabilityVisual(key) {
  if (key === 'workflow') return `<div class="proc-mini-workflow"><header><span>PROCESSO</span><b>Atendimento comercial</b></header><div><span class="done"><i>01</i><b>Definir</b><em>Concluído</em></span><span class="active"><i>02</i><b>Executar</b><em>Etapa atual</em></span><span><i>03</i><b>Monitorar</b><em>A seguir</em></span><span><i>04</i><b>Otimizar</b><em>A seguir</em></span></div><footer><small>Etapa atual</small><strong>Executar</strong></footer></div>`;
  if (key === 'definicao') return `<div class="proc-mini-nodes"><span><i>1</i><b>Entrada</b></span><u></u><span><i>2</i><b>Análise</b></span><u></u><span><i>3</i><b>Execução</b></span></div>`;
  if (key === 'sequencia') return `<div class="proc-mini-sequence"><span class="done"><i>✓</i><b>Etapa 01</b></span><span class="active"><i>2</i><b>Etapa 02</b></span><span><i>3</i><b>Etapa 03</b></span></div>`;
  if (key === 'responsaveis') return `<div class="proc-mini-owner"><span><i>EC</i><div><small>Responsável atual</small><b>Equipe Comercial</b></div></span><footer>Execução · Etapa 2 de 4</footer></div>`;
  if (key === 'monitoramento') return `<div class="proc-mini-monitor"><span><small>Ativos</small><b>11</b></span><span><small>Em execução</small><b>8</b></span><span class="attention"><small>Aguardando</small><b>3</b></span></div>`;
  if (key === 'padronizacao') return `<div class="proc-mini-standard"><span>${icon('i-check', 'i')}<b>Mesma entrada</b></span><span>${icon('i-check', 'i')}<b>Mesma sequência</b></span><span>${icon('i-check', 'i')}<b>Mesmo acompanhamento</b></span></div>`;
  if (key === 'transparencia') return `<div class="proc-mini-status"><span><i class="run"></i><b>Em andamento</b><small>8 processos</small></span><span><i class="wait"></i><b>Aguardando</b><small>3 processos</small></span><span><i class="done"></i><b>Concluídos</b><small>24 processos</small></span></div>`;
  return `<div class="proc-mini-improve"><span><small>Antes</small><b>Rotina dispersa</b></span><i>→</i><span><small>Depois</small><b>Fluxo acompanhado</b></span></div>`;
}

function heroProduct() {
  return `<div class="proc-console" aria-label="Exemplo ilustrativo de um workflow"><div class="proc-console-top"><span><i></i><i></i><i></i></span><b>Gestão de Processos</b><em>Workflow</em></div><div class="proc-console-body"><header><div><small>WORKFLOW</small><strong>Atendimento comercial</strong></div><span>Em andamento</span></header><div class="proc-console-kpis"><span><small>Etapas</small><b>4</b></span><span><small>Em andamento</small><b>8</b></span><span><small>Concluídos</small><b>24</b></span><span class="attention"><small>Aguardando ação</small><b>3</b></span></div><section><span class="done"><i>1</i><b>Entrada</b></span><u></u><span class="done"><i>2</i><b>Análise</b></span><u></u><span class="active"><i>3</i><b>Execução</b></span><u></u><span><i>4</i><b>Conclusão</b></span></section></div></div><div class="proc-note">${icon('i-processos', 'i')}<span><small>Etapa atual</small><b>Execução</b></span></div><div class="proc-note">${icon('i-rh', 'i')}<span><small>Responsável</small><b>Equipe Comercial</b></span></div><div class="proc-note">${icon('i-check', 'i')}<span><small>Andamento</small><b>Fluxo acompanhado</b></span></div>`;
}

function processesScreen() {
  const rows = [
    ['Atendimento comercial', 'Análise', 'Comercial', 'Em andamento', 'run'],
    ['Cadastro de cliente', 'Execução', 'Administrativo', 'Em andamento', 'run'],
    ['Revisão interna', 'Monitoramento', 'Equipe responsável', 'Acompanhando', 'wait'],
    ['Fluxo comercial', 'Conclusão', 'Comercial', 'Concluído', 'done'],
  ];
  return `<div class="proc-screen" role="img" aria-label="Exemplo ilustrativo da central de processos"><div class="proc-screen-bar"><span><i></i><i></i><i></i></span><b>Gestão de Processos</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="proc-screen-body"><div class="proc-screen-toolbar"><span>Todos os processos</span><span>Etapas e responsáveis</span><b>Acompanhar fluxos</b></div><div class="proc-screen-kpis"><span><small>Processos ativos</small><b>11</b></span><span><small>Em execução</small><b>8</b></span><span class="attention"><small>Aguardando</small><b>3</b></span><span><small>Concluídos hoje</small><b>4</b></span></div><div class="proc-screen-layout"><div class="proc-screen-scroll"><div class="proc-screen-table"><header><span>Processo</span><span>Etapa atual</span><span>Responsável</span><span>Situação</span></header>${rows.map((row, index) => `<article class="${index === 0 ? 'active' : ''}"><b>${esc(row[0])}</b><span>${esc(row[1])}</span><span>${esc(row[2])}</span><em class="${row[4]}">${esc(row[3])}</em></article>`).join('')}</div></div><aside><span>PROCESSO SELECIONADO</span><h3>Atendimento comercial</h3><div><small>Etapa</small><b>Análise</b></div><div><small>Responsável</small><b>Comercial</b></div><div><small>Sequência</small><b>2 de 4</b></div><footer><small>Situação</small><b>Em andamento</b></footer></aside></div></div></div>`;
}

export function renderProcesses(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Gestão de Processos' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Gestão de Processos</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero processes-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Gestão de Processos</p><h1>Transforme uma rotina que depende de lembrança em um fluxo que mostra o que vem agora.</h1><p class="lede">Defina etapas, organize responsáveis e acompanhe a execução para padronizar atividades e reduzir erros e retrabalho.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_processos_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como o fluxo avança${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Etapa e responsável visíveis</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product processes-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section processes-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro processes-intro reveal"><p class="kicker">Da lembrança ao fluxo</p><h2>Cada rotina com etapas, sequência e acompanhamento.</h2><p>O workflow torna explícito o caminho de uma atividade: o que precisa acontecer, quem conduz a etapa e onde o processo está.</p></div><div id="capacidades" class="module-system-bento processes-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card processes-cap-card processes-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading processes-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section processes-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Ciclo do workflow</p><h2>Definir, executar, monitorar <span>e otimizar.</span></h2><p class="lede">Quatro etapas são suficientes para transformar a rotina em um processo acompanhado e evolutivo.</p></div></div><div class="module-system-flow processes-flow reveal" data-module-flow><div class="module-system-flow-track processes-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step processes-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail processes-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section processes-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Onde está cada processo e qual é a etapa atual?</h2><p class="lede">A central aproxima processo, etapa, responsável e situação, com os detalhes da rotina selecionada no painel lateral.</p></div></div><div class="module-system-screen-stage processes-screen-stage reveal">${processesScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Processo identificado</b><small>A equipe sabe qual rotina está sendo executada.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Etapa atual</b><small>O fluxo mostra onde a atividade está.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Responsabilidade clara</b><small>Cada etapa mantém quem conduz o trabalho.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Andamento visível</b><small>O processo deixa de depender apenas da memória.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Quando o processo pede clareza</p><h2>Situações que melhoram com sequência e acompanhamento.</h2></div></div><div class="module-system-situations processes-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const crm = modules.crm;
  const integrationSection = `<section class="section processes-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Workflow em contexto</p><h2>Etapas, responsáveis e acompanhamento no centro da execução.</h2><p class="lede">Os conceitos internos do workflow aparecem como capacidades; somente o CRM representa uma integração comprovada com outro módulo.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium processes-ecosystem reveal" data-eco-count="4"><div class="module-system-ecosystem-head"><span><i></i> Workflow conectado</span><b>Da etapa ao acompanhamento</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C450 215 450 168 450 123"/><path d="M450 263 C350 270 260 300 144 325"/><path d="M450 263 C550 270 640 300 756 325"/><path d="M450 263 C450 335 450 405 450 470"/></svg><div class="module-system-eco-center processes-eco-center"><span>${icon('i-processos', 'i')}</span><small>Execução orientada</small><b>Processos</b><em>Workflow e responsáveis</em></div><div class="module-system-eco-node module-system-eco-node--info processes-eco-node processes-eco-node--info" style="--x:50%;--y:22%"><span>${icon('i-grid', 'i')}</span><div><em>Capacidade</em><b>Etapas</b><small>O processo é estruturado em uma sequência definida.</small></div></div><div class="module-system-eco-node module-system-eco-node--info processes-eco-node processes-eco-node--info" style="--x:16%;--y:58%"><span>${icon('i-rh', 'i')}</span><div><em>Capacidade</em><b>Responsáveis</b><small>Cada etapa mantém o contexto de quem conduz a atividade.</small></div></div><div class="module-system-eco-node module-system-eco-node--info processes-eco-node processes-eco-node--info" style="--x:84%;--y:58%"><span>${icon('i-check', 'i')}</span><div><em>Capacidade</em><b>Acompanhamento</b><small>O andamento fica visível durante a execução.</small></div></div><a class="module-system-eco-node processes-eco-node" style="--x:50%;--y:84%" href="${crm.slug}.html"><span>${icon(crm.icon, 'i')}</span><div><em>Módulo integrado</em><b>CRM</b><small>Workflows apoiam as etapas internas do atendimento comercial.</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a></div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Gestão de Processos</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja como workflows, etapas, responsáveis e acompanhamento podem padronizar atividades e dar visibilidade à execução.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_processos_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'processes.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
