import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'necessidades', icon: 'i-compras', title: 'Necessidades de compra', text: 'Reúna o que precisa ser comprado, a origem da demanda e a data necessária.', dominant: true },
  { key: 'cotacoes', icon: 'i-grid', title: 'Cotações', text: 'Solicite e registre preços, condições e prazos dos fornecedores.' },
  { key: 'comparativo', icon: 'i-custos', title: 'Comparativo de fornecedores', text: 'Compare preço, prazo e condição antes de escolher.' },
  { key: 'pedidos', icon: 'i-compras', title: 'Pedidos de compra', text: 'Transforme a cotação escolhida em pedido com acompanhamento.' },
  { key: 'pendentes', icon: 'i-processos', title: 'Recebimentos pendentes', text: 'Saiba o que ainda deve chegar e o que está atrasado.' },
  { key: 'historico', icon: 'i-grid', title: 'Histórico de compras', text: 'Consulte últimas condições e preços praticados por item.' },
  { key: 'condicoes', icon: 'i-financeiro', title: 'Condições e prazos', text: 'Avalie vencimentos, parcelas e previsão de entrega.' },
  { key: 'entrada', icon: 'i-wms', title: 'Entrada de mercadorias', text: 'Receba documentos e atualize estoque, fiscal e financeiro.' },
];

const flow = [
  { label: 'Necessidade', input: 'Demanda, estoque e produção', control: 'Item, quantidade e data', output: 'Solicitação para cotar' },
  { label: 'Cotação', input: 'Itens e fornecedores', control: 'Preço, prazo e condição', output: 'Propostas comparáveis' },
  { label: 'Fornecedor', input: 'Propostas recebidas', control: 'Escolha e aprovação', output: 'Condição selecionada' },
  { label: 'Pedido', input: 'Cotação aprovada', control: 'Itens, valores e entrega', output: 'Compra confirmada' },
  { label: 'Recebimento', input: 'Pedido e documento fiscal', control: 'Quantidade, XML e entrada', output: 'Estoque e gestão atualizados' },
];

const situations = [
  ['A produção precisa de material', 'A necessidade chega com item, quantidade e data para orientar a compra antes da falta.'],
  ['Três fornecedores enviaram preços diferentes', 'Preço, prazo e condição ficam lado a lado para uma escolha documentada.'],
  ['O prazo é melhor, mas o preço é maior', 'O comparativo ajuda a avaliar o impacto da condição completa, não apenas do menor valor.'],
  ['Um pedido está atrasado', 'Previsão e situação deixam visível o que deveria ter chegado e ainda está pendente.'],
  ['A entrega chegou parcialmente', 'O recebido é registrado sem perder o saldo que o fornecedor ainda precisa entregar.'],
  ['A mercadoria precisa entrar no estoque', 'O recebimento conecta documento, quantidade, estoque, fiscal e financeiro.'],
];

const connections = [
  { key: 'pcpm', label: 'PCPM', text: 'Necessidades de materiais ajudam a direcionar o que comprar.', eyebrow: 'Planejamento', x: 18, y: 28 },
  { key: 'wms', label: 'Estoque e WMS', text: 'Recebimentos atualizam saldo, lote e localização.', eyebrow: 'Recebimento', x: 82, y: 28 },
  { key: 'financeiro', label: 'Financeiro', text: 'Condições e parcelas seguem para os compromissos a pagar.', eyebrow: 'Compromissos', x: 18, y: 72 },
  { key: 'contabilidade', label: 'Fiscal e Contábil', text: 'Documentos de entrada geram os movimentos correspondentes.', eyebrow: 'Documentos', x: 82, y: 72 },
];

function capabilityVisual(key) {
  if (key === 'necessidades') return `<div class="buy-mini-needs"><header><span>Necessidades abertas</span><b>12 itens</b></header><div><span><i style="--w:86%"></i><b>Aço SAE 1020</b><small>1.200 kg · até 28/09</small></span><span><i style="--w:62%"></i><b>Rolamento 6204</b><small>240 un. · até 30/09</small></span><span><i style="--w:38%"></i><b>Correia AX-42</b><small>80 un. · até 02/10</small></span></div><footer><span>6 itens do PCPM</span><b>3 aguardando cotação</b></footer></div>`;
  if (key === 'cotacoes') return `<div class="buy-mini-quotes"><span><b>Fornecedor A</b><small>R$ 36.840</small></span><span><b>Fornecedor B</b><small>R$ 38.120</small></span><span><b>Fornecedor C</b><small>R$ 35.990</small></span></div>`;
  if (key === 'comparativo') return `<div class="buy-mini-compare"><span><small>Preço</small><b>A</b></span><span><small>Prazo</small><b>B</b></span><span class="best"><small>Condição</small><b>A</b></span></div>`;
  if (key === 'pedidos') return `<div class="buy-mini-order"><span>PC 008419 <b>Recebido</b></span><span>PC 008420 <b>Em trânsito</b></span><span>PC 008421 <b>Aprovação</b></span></div>`;
  if (key === 'pendentes') return `<div class="buy-mini-pending"><span><i style="--w:78%"></i><b>18/20 itens</b><small>Entrega parcial</small></span><span class="late"><i style="--w:42%"></i><b>7/16 itens</b><small>2 dias em atraso</small></span></div>`;
  if (key === 'historico') return `<div class="buy-mini-history"><span><small>Última compra</small><b>R$ 82,40</b></span><i>→</i><span><small>Cotação atual</small><b>R$ 79,90</b></span></div>`;
  if (key === 'condicoes') return `<div class="buy-mini-terms"><span>28 dias</span><span>35 dias</span><span>42 dias</span></div>`;
  return `<div class="buy-mini-entry"><span class="done">${icon('i-check', 'i')}XML localizado</span><i></i><span>${icon('i-wms', 'i')}Entrada no estoque</span><i></i><span>${icon('i-financeiro', 'i')}Financeiro</span></div>`;
}

function heroProduct() {
  return `<div class="buy-order" aria-label="Exemplo ilustrativo de um pedido de compra aguardando aprovação"><div class="buy-order-top"><span><i></i><i></i><i></i></span><b>Compras</b><em>Pedido PC 008421</em></div><div class="buy-order-body"><div class="buy-supplier"><div><small>Fornecedor</small><strong>Metalúrgica Alfa</strong></div><span>Aguardando aprovação</span></div><div class="buy-main-kpis"><div><small>Valor do pedido</small><b>R$ 36.840,00</b></div><div><small>Itens</small><b>18</b></div></div><div class="buy-delivery"><div><small>Previsão de entrega</small><b>30/09</b></div><div><small>Condição</small><b>28 / 35 / 42 dias</b></div></div><div class="buy-next"><span>${icon('i-check', 'i')}</span><div><small>Próxima decisão</small><b>Aprovar pedido de compra</b></div><em>3 cotações analisadas</em></div></div></div>
  <div class="buy-float buy-float--quotes">${icon('i-grid', 'i')}<span><small>Cotações comparadas</small><b>3 fornecedores</b></span></div><div class="buy-float buy-float--deadline">${icon('i-check', 'i')}<span><small>Prazo selecionado</small><b>7 dias</b></span></div><div class="buy-float buy-float--need">${icon('i-pcpm', 'i')}<span><small>Necessidade do PCPM</small><b>6 itens</b></span></div>`;
}

function purchaseScreen() {
  const rows = [
    ['Metalúrgica Alfa', 'R$ 36.840,00', '7 dias', '28/35/42', 'Selecionado', 'ok'],
    ['Fornecedor Beta', 'R$ 35.990,00', '14 dias', '28 dias', 'Menor preço', 'run'],
    ['Fornecedor Gama', 'R$ 38.120,00', '5 dias', '21/28 dias', 'Melhor prazo', 'wait'],
  ];
  return `<div class="buy-screen" role="img" aria-label="Exemplo ilustrativo do comparativo de fornecedores"><div class="buy-screen-bar"><span><i></i><i></i><i></i></span><b>Compras · Comparativo de cotação</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="buy-screen-body"><div class="buy-screen-toolbar"><span>Cotação · 004812</span><span>18 itens</span><b>Gerar pedido</b></div><div class="buy-screen-kpis"><div><small>Necessidade</small><b>30/09</b></div><div><small>Fornecedores</small><b>3</b></div><div><small>Melhor condição</small><b>28 / 35 / 42</b></div></div><div class="buy-screen-scroll"><div class="buy-screen-table"><div class="th"><span>Fornecedor</span><span>Valor</span><span>Prazo</span><span>Condição</span><span>Análise</span></div>${rows.map((r) => `<div class="tr"><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]}</span><span>${r[3]}</span><span class="${r[5]}">${r[4]}</span></div>`).join('')}</div></div><footer><span>Histórico dos últimos 3 preços disponível</span><b>Condição selecionada</b></footer></div></div>`;
}

export function renderPurchases(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Compras e Suprimentos' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Compras e Suprimentos</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integrações</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero purchases-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Compras e suprimentos</p><h1>Compre com necessidade, preço e prazo visíveis antes de fechar o pedido.</h1><p class="lede">Da necessidade ao recebimento, o Infoline reúne cotações, fornecedores, pedidos e entradas para comprar com contexto e manter as áreas conectadas.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_compras_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como a compra avança${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Necessidade e cotação conectadas</li><li>${icon('i-grid', 'i i-sm')}Parte do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product purchases-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section purchases-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro purchases-intro reveal"><p class="kicker">Compras na prática</p><h2>Saiba o que comprar. Compare as condições. Acompanhe o que falta chegar.</h2><p>A necessidade pode nascer da produção, do estoque ou da operação. A compra organiza cotação, escolha, pedido e recebimento sem perder origem, prazo ou impacto.</p></div><div id="capacidades" class="module-system-bento purchases-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card purchases-cap-card purchases-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading purchases-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section purchases-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Da necessidade ao recebimento</p><h2>A compra avança com <span>preço, prazo e origem visíveis.</span></h2><p class="lede">Passe por cada etapa para entender o que entra, o que o sistema controla e qual informação segue adiante.</p></div></div><div class="module-system-flow purchases-flow reveal" data-module-flow><div class="module-system-flow-track purchases-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step purchases-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail purchases-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section purchases-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Compare fornecedores antes de transformar a cotação em pedido.</h2><p class="lede">Preço, prazo, condição e histórico ficam próximos para a equipe escolher e justificar a melhor compra.</p></div></div><div class="module-system-screen-stage purchases-screen-stage reveal">${purchaseScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Necessidade registrada</b><small>Data e quantidade orientam a cotação.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Fornecedores comparados</b><small>As propostas permanecem lado a lado.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Preço e prazo</b><small>A escolha considera a condição completa.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Pedido preparado</b><small>A cotação escolhida segue para aprovação.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Onde esse controle faz diferença</p><h2>Situações de compra que pedem contexto antes da decisão.</h2></div></div><div class="module-system-situations purchases-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const integrationSection = `<section class="section purchases-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">ERP integrado</p><h2>A compra abastece toda a operação.</h2><p class="lede">Necessidade, recebimento, estoque, compromissos e documentos continuam conectados ao mesmo fluxo.</p></div></div><div class="module-system-ecosystem purchases-ecosystem reveal"><div class="purchases-ecosystem-top"><span><i></i> Fluxo integrado</span><b>Da necessidade à entrada</b></div><svg viewBox="0 0 900 480" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="purchases-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="240" rx="205" ry="142"/><path d="M450 240 C360 205 285 164 162 134"/><path d="M450 240 C540 205 615 164 738 134"/><path d="M450 240 C360 275 285 316 162 346"/><path d="M450 240 C540 275 615 316 738 346"/></svg><div class="module-system-eco-center purchases-eco-center"><span>${icon('i-compras', 'i')}</span><small>Abastecimento</small><b>Compras</b><em>Da necessidade ao recebimento</em></div>${connections.map((item) => { const mod = modules[item.key]; return `<a class="module-system-eco-node purchases-eco-node purchases-eco-node--${item.key}" style="--x:${item.x}%;--y:${item.y}%" href="${mod.slug}.html"><span>${icon(mod.icon, 'i')}</span><div><em>${esc(item.eyebrow)}</em><b>${esc(item.label)}</b><small>${esc(item.text)}</small></div>${icon('i-arrow-right', 'i purchases-eco-arrow')}</a>`; }).join('')}<div class="purchases-ecosystem-foot"><span>Planejamento</span><i></i><span>Estoque</span><i></i><span>Compromissos</span><i></i><span>Documentos</span></div></div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre Compras e Suprimentos</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja necessidade, cotação, pedido e recebimento funcionando na rotina da sua empresa.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_compras_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'purchases.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
