import { esc, icon } from '../lib.mjs';
import { head, orgSchema, faqSchema } from '../head.mjs';
import { header, footer, breadcrumb } from '../layout.mjs';
import { modules } from '../content.mjs';

const capabilities = [
  { key: 'cobranca', icon: 'i-whatsapp', title: 'Cobrança pelo WhatsApp', text: 'Leve o boleto da rotina financeira ao canal que o cliente acompanha, com o envio e o resultado registrados.', dominant: true },
  { key: 'boleto', icon: 'i-contabilidade', title: 'Envio de boleto', text: 'Inclua documento, parcela e link de acesso ao PDF.' },
  { key: 'consulta', icon: 'i-grid', title: 'Histórico e consulta', text: 'Pesquise mensagens por período, telefone ou texto.' },
  { key: 'status', icon: 'i-check', title: 'Status da comunicação', text: 'Acompanhe quando a mensagem foi enviada, entregue e lida.' },
  { key: 'excecoes', icon: 'i-phone', title: 'Controle de exceções', text: 'Identifique número inválido ou ausente e registre o motivo do não envio.' },
  { key: 'financeiro', icon: 'i-financeiro', title: 'Integração financeira', text: 'O título em cobrança mantém o contexto da mensagem enviada ao cliente.' },
];

const flow = [
  { label: 'Título', input: 'Título em cobrança', control: 'Documento e parcela', output: 'Boleto identificado' },
  { label: 'Boleto', input: 'Boleto identificado', control: 'Link de acesso ao PDF', output: 'Mensagem preparada' },
  { label: 'WhatsApp', input: 'Mensagem e número do cliente', control: 'Validade do contato', output: 'Envio realizado' },
  { label: 'Entrega', input: 'Mensagem enviada', control: 'Enviado, entregue e lido', output: 'Situação registrada' },
  { label: 'Acompanhamento', input: 'Histórico dos envios', control: 'Período, telefone ou texto', output: 'Cobrança acompanhável' },
];

const situations = [
  ['O boleto foi emitido, mas ainda não chegou ao cliente', 'A mensagem leva o documento e o link de acesso pelo WhatsApp.'],
  ['A equipe não sabe se a mensagem foi entregue', 'Os estados enviado, entregue e lido deixam o resultado da comunicação visível.'],
  ['O cliente pede novamente o boleto', 'O histórico ajuda a localizar a mensagem e acompanhar o envio anterior.'],
  ['O número informado é inválido', 'O motivo do não envio fica registrado para a correção do cadastro.'],
  ['O cliente não possui telefone cadastrado', 'A exceção aparece para tratamento antes de uma nova tentativa.'],
  ['É preciso conferir as cobranças de um período', 'A consulta pode ser feita por data, telefone ou texto da mensagem.'],
];

function capabilityVisual(key) {
  if (key === 'cobranca') return `<div class="wapp-mini-chat"><header><span>${icon('i-whatsapp', 'i')}</span><div><small>COBRANÇA</small><b>Distribuidora Alfa</b></div><em>Online</em></header><section><p>Olá! O boleto do documento 00018425 está disponível.</p><a>Visualizar boleto <b>↗</b></a><small>10:42 <i>✓✓</i></small></section><footer><span>Mensagem lida</span><b>10:44</b></footer></div>`;
  if (key === 'boleto') return `<div class="wapp-mini-doc"><span>${icon('i-contabilidade', 'i')}</span><div><small>DOCUMENTO</small><b>00018425 · Parcela 01</b><em>PDF disponível</em></div></div>`;
  if (key === 'consulta') return `<div class="wapp-mini-search"><span>${icon('i-grid', 'i')} Setembro de 2026</span><span>${icon('i-phone', 'i')} (41) 99999-0184</span><span class="active">3 mensagens encontradas</span></div>`;
  if (key === 'status') return `<div class="wapp-mini-status"><span class="done"><i>✓</i><b>Enviado</b></span><u></u><span class="done"><i>✓</i><b>Entregue</b></span><u></u><span class="done"><i>✓</i><b>Lido</b></span></div>`;
  if (key === 'excecoes') return `<div class="wapp-mini-exception"><span>!</span><div><small>NÃO ENVIADO</small><b>Número de WhatsApp inválido</b><em>Corrija o cadastro para reenviar.</em></div></div>`;
  return `<div class="wapp-mini-financial"><div><small>Título</small><b>00018425</b></div><i>→</i><div><small>Mensagem</small><b>Boleto vinculado</b></div></div>`;
}

function heroProduct() {
  return `<div class="wapp-console" aria-label="Exemplo ilustrativo de cobrança enviada pelo WhatsApp"><div class="wapp-console-top"><span><i></i><i></i><i></i></span><b>Cobrança pelo WhatsApp</b><em>Título 00018425</em></div><div class="wapp-console-body"><section class="wapp-title-card"><header><div><small>CLIENTE</small><strong>Distribuidora Alfa</strong></div><span>Boleto enviado</span></header><div><span><small>Vencimento</small><b>30/09/2026</b></span><span><small>Valor</small><b>R$ 8.420,00</b></span><span><small>Documento</small><b>00018425</b></span><span><small>Parcela</small><b>01</b></span></div></section><section class="wapp-chat"><header><span>${icon('i-whatsapp', 'i')}</span><div><b>Distribuidora Alfa</b><small>WhatsApp</small></div></header><div class="wapp-bubble"><p>Olá! Seu boleto está disponível.</p><a>Visualizar boleto <b>↗</b></a><small>10:42 <i>✓✓</i></small></div></section></div></div><div class="wapp-note"><i>✓</i><span><small>Enviado</small><b>10:42</b></span></div><div class="wapp-note"><i>✓✓</i><span><small>Entregue</small><b>10:43</b></span></div><div class="wapp-note"><i>✓✓</i><span><small>Lido</small><b>10:44</b></span></div>`;
}

function whatsappScreen() {
  const rows = [
    ['Distribuidora Alfa', '00018425', '30/09/2026', 'R$ 8.420,00', 'Lido', 'read'],
    ['Comercial Beta', '00018431', '01/10/2026', 'R$ 3.190,40', 'Entregue', 'delivered'],
    ['Indústria Gama', '00018437', '02/10/2026', 'R$ 12.780,00', 'Enviado', 'sent'],
    ['Cliente sem número', '00018442', '03/10/2026', 'R$ 1.486,90', 'Não enviado', 'failed'],
  ];
  return `<div class="wapp-screen" role="img" aria-label="Exemplo ilustrativo da central de mensagens de cobrança"><div class="wapp-screen-bar"><span><i></i><i></i><i></i></span><b>Mensagens de cobrança</b><em class="module-system-illustrative-label">Tela ilustrativa</em></div><div class="wapp-screen-body"><div class="wapp-screen-toolbar"><span>Envios · 01/09/2026 a 30/09/2026</span><span>Telefone ou mensagem</span><b>Consultar envios</b></div><div class="wapp-screen-layout"><div class="wapp-screen-scroll"><div class="wapp-screen-table"><header><span>Cliente</span><span>Título</span><span>Vencimento</span><span>Valor</span><span>Status</span></header>${rows.map((row, index) => `<article class="${index === 0 ? 'active' : ''}"><b>${esc(row[0])}</b><span>${esc(row[1])}</span><span>${esc(row[2])}</span><span>${esc(row[3])}</span><em class="${row[5]}">${esc(row[4])}</em></article>`).join('')}</div></div><aside><span>ENVIO SELECIONADO</span><h3>Distribuidora Alfa</h3><div><small>Título</small><b>00018425 · Parcela 01</b></div><div><small>Boleto</small><b>Link do PDF enviado</b></div><div><small>WhatsApp</small><b>(41) 99999-0184</b></div><footer><small>Status da comunicação</small><b>✓✓ Lido · 10:44</b></footer></aside></div></div></div>`;
}

export function renderWhatsapp(m) {
  const headHtml = head({ title: m.seoTitle, description: m.seoDesc, path: `${m.slug}.html`, schemas: [orgSchema(), faqSchema(m.faq)] });
  const bc = breadcrumb([{ label: 'Início', href: 'index.html' }, { label: 'Soluções', href: 'solucoes.html' }, { label: 'Integração WhatsApp' }]);
  const localNav = `<nav class="module-nav" aria-label="Nesta solução"><div class="container module-nav-inner"><span>Integração WhatsApp</span><div><a href="#visao-geral">Visão geral</a><a href="#capacidades">Capacidades</a><a href="#fluxo">Fluxo</a><a href="#tela">Tela</a><a href="#situacoes">Situações</a><a href="#integracoes">Integração</a><a href="#faq">FAQ</a></div></div></nav>`;
  const hero = `<section class="mod-hero module-system-hero wapp-hero"><div class="container mod-hero-inner"><div class="reveal"><span class="mod-hero-icon">${icon(m.icon, 'i i-lg')}</span><p class="kicker">Cobrança pelo WhatsApp</p><h1>O boleto saiu do Financeiro. O cliente recebeu?</h1><p class="lede">Envie a cobrança com o link do boleto e acompanhe se a mensagem foi enviada, entregue ou lida — sem separar a comunicação da rotina financeira.</p><div class="mod-hero-cta"><a class="button button-primary" href="index.html#contato" data-track="cta_click" data-label="mod_whatsapp_demo">Agendar uma demonstração</a><a class="text-link" href="#capacidades">Ver como funciona${icon('i-chevron-right', 'i')}</a></div><ul class="mod-hero-meta"><li>${icon('i-check', 'i i-sm')}Boleto e comunicação conectados</li><li>${icon('i-grid', 'i i-sm')}Integração do ERP Infoline</li></ul></div><div class="mod-hero-product module-system-hero-product wapp-hero-product reveal"><span class="mod-product-label">Tela ilustrativa</span>${heroProduct()}<small>Representação ilustrativa. Nenhum dado real é exibido.</small></div></div></section>`;
  const capabilitiesSection = `<section class="section wapp-capabilities" id="visao-geral"><div class="container"><div class="module-system-intro wapp-intro reveal"><p class="kicker">Cobrança acompanhável</p><h2>Do título financeiro à mensagem que chega ao cliente.</h2><p>A integração reduz a rotina manual de envio, preserva o vínculo com o boleto e mostra o resultado de cada comunicação.</p></div><div id="capacidades" class="module-system-bento wapp-bento reveal">${capabilities.map((item) => `<article class="module-system-cap-card wapp-cap-card wapp-cap-card--${item.key}${item.dominant ? ' is-dominant' : ''}"><div class="module-system-cap-heading wapp-cap-heading"><span>${icon(item.icon, 'i')}</span><div><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></div></div>${capabilityVisual(item.key)}</article>`).join('')}</div></div></section>`;
  const flowSection = `<section class="section section--dark module-system-flow-section wapp-flow-section" id="fluxo"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Da cobrança ao acompanhamento</p><h2>O boleto segue para o cliente <span>com o estado da comunicação visível.</span></h2><p class="lede">Clique nas etapas para acompanhar o que entra, o que é controlado e o que segue no fluxo.</p></div></div><div class="module-system-flow wapp-flow reveal" data-module-flow><div class="module-system-flow-track wapp-flow-track">${flow.map((step, index) => `<button type="button" class="module-system-flow-step wapp-flow-step${index === 0 ? ' is-active' : ''}" aria-pressed="${index === 0 ? 'true' : 'false'}" data-flow-input="${esc(step.input)}" data-flow-control="${esc(step.control)}" data-flow-output="${esc(step.output)}"><span>${index + 1}</span><b>${esc(step.label)}</b></button>`).join('')}</div><div class="module-system-flow-detail wapp-flow-detail" aria-live="polite"><div><small>Entra</small><b data-flow-detail="input">${esc(flow[0].input)}</b></div><div><small>O sistema controla</small><b data-flow-detail="control">${esc(flow[0].control)}</b></div><div><small>Segue para a próxima etapa</small><b data-flow-detail="output">${esc(flow[0].output)}</b></div></div></div></div></section>`;
  const screenSection = `<section class="section module-system-screen-section wapp-screen-section" id="tela"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Veja o produto</p><h2>Qual cobrança foi enviada — e o que aconteceu depois?</h2><p class="lede">A central reúne cliente, título, vencimento, valor e estado da comunicação, com o detalhe da mensagem selecionada.</p></div></div><div class="module-system-screen-stage wapp-screen-stage reveal">${whatsappScreen()}<div class="module-system-hotspot module-system-hotspot--1"><i>1</i><span><b>Origem financeira</b><small>O título mantém o contexto da cobrança.</small></span></div><div class="module-system-hotspot module-system-hotspot--2"><i>2</i><span><b>Boleto vinculado</b><small>Documento, parcela e link seguem juntos.</small></span></div><div class="module-system-hotspot module-system-hotspot--3"><i>3</i><span><b>Envio pelo WhatsApp</b><small>A mensagem usa o contato do cliente.</small></span></div><div class="module-system-hotspot module-system-hotspot--4"><i>4</i><span><b>Status da comunicação</b><small>Enviado, entregue e lido ficam visíveis.</small></span></div></div></div></section>`;
  const situationsSection = `<section class="section section--mist" id="situacoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Quando a cobrança pede acompanhamento</p><h2>Situações que deixam de depender de envio manual e conferência dispersa.</h2></div></div><div class="module-system-situations wapp-situations reveal">${situations.map((item, index) => `<article><span>0${index + 1}</span><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div></div></section>`;
  const financial = modules.financeiro;
  const integrationSection = `<section class="section wapp-integration" id="integracoes"><div class="container"><div class="section-head reveal"><div class="section-head-text"><p class="kicker">Integração em contexto</p><h2>O WhatsApp amplia uma rotina que começa no Financeiro.</h2><p class="lede">Cliente, boleto e status são capacidades da comunicação. O Financeiro é o módulo conectado que dá origem à cobrança.</p></div></div><div class="module-system-ecosystem module-system-ecosystem--premium wapp-ecosystem reveal" data-eco-count="4"><div class="module-system-ecosystem-head"><span><i></i> Comunicação integrada</span><b>Do título ao acompanhamento</b></div><svg viewBox="0 0 900 560" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="module-eco-line" x1="0" x2="1"><stop offset="0" stop-color="#38c8ff"/><stop offset="1" stop-color="#4d7dff"/></linearGradient></defs><ellipse cx="450" cy="270" rx="270" ry="174"/><path d="M450 263 C450 215 450 168 450 123"/><path d="M450 263 C350 270 260 300 144 325"/><path d="M450 263 C550 270 640 300 756 325"/><path d="M450 263 C450 335 450 405 450 470"/></svg><div class="module-system-eco-center wapp-eco-center"><span>${icon('i-whatsapp', 'i')}</span><small>Comunicação</small><b>WhatsApp</b><em>Cobrança acompanhável</em></div><div class="module-system-eco-node module-system-eco-node--info wapp-eco-node wapp-eco-node--info" style="--x:50%;--y:22%"><span>${icon('i-comercial', 'i')}</span><div><em>Capacidade</em><b>Cliente</b><small>Contato ligado à mensagem de cobrança.</small></div></div><div class="module-system-eco-node module-system-eco-node--info wapp-eco-node wapp-eco-node--info" style="--x:16%;--y:58%"><span>${icon('i-contabilidade', 'i')}</span><div><em>Capacidade</em><b>Boleto</b><small>Documento, parcela e link de acesso ao PDF.</small></div></div><div class="module-system-eco-node module-system-eco-node--info wapp-eco-node wapp-eco-node--info" style="--x:84%;--y:58%"><span>${icon('i-check', 'i')}</span><div><em>Capacidade</em><b>Status</b><small>Enviado, entregue e lido.</small></div></div><a class="module-system-eco-node wapp-eco-node" style="--x:50%;--y:84%" href="${financial.slug}.html"><span>${icon(financial.icon, 'i')}</span><div><em>Origem da cobrança</em><b>Financeiro</b><small>O título em cobrança dá origem ao envio.</small></div>${icon('i-arrow-right', 'i module-system-ecosystem-arrow')}</a></div></div></section>`;
  const faqSection = `<section class="section" id="faq"><div class="container" style="max-width:900px"><div class="section-head reveal" style="display:block"><p class="kicker">Perguntas frequentes</p><h2>Sobre a Integração WhatsApp</h2></div><div class="faq-list reveal">${m.faq.map(([q, a], index) => `<details class="faq-item"${index === 0 ? ' open' : ''}><summary>${esc(q)}${icon('i-plus', 'i')}</summary><p class="faq-item-a">${esc(a)}</p></details>`).join('')}</div></div></section>`;
  const ctaSection = `<section class="section"><div class="container"><div class="cta-banner reveal"><h2>${esc(m.cta)}</h2><p>Veja como o boleto pode sair da rotina financeira e chegar ao cliente com o acompanhamento do envio no ERP.</p><div class="cta-banner-actions"><a class="button button-light" href="index.html#contato" data-track="cta_click" data-label="mod_whatsapp_bottom">Agendar demonstração</a><a class="button button-ghost-dark" href="solucoes.html">Ver outras soluções</a></div></div></div></section>`;
  const body = `${header({ current: m.slug, variant: 'internal' })}${bc}<main id="conteudo">${hero}${localNav}${capabilitiesSection}${flowSection}${screenSection}${situationsSection}${integrationSection}${faqSection}${ctaSection}</main>${footer()}`;
  return { headHtml, body, styles: ['module.css', 'module-system.css', 'whatsapp.css'], pageType: 'module', moduleKey: m.key, solutionGroup: m.group };
}
